<!--TODO: Make left nav float-->
<template>
  <b-container fluid="sm">
    <b-row class="text-left">
      <b-col class="text-left" cols="2">
        <div class="sidebar">
          <b-card>
            <b-nav vertical>
              <b-nav-item @click="goto('intro')">Introduction</b-nav-item>
              <b-nav-item @click="goto('class')">Classical Evolutionary Theories of Aging</b-nav-item>
              <b-nav-item @click="goto('life')">Life History Theory</b-nav-item>
              <b-nav-item @click="goto('empirical')">Empirical Evidence</b-nav-item>
              <b-nav-item @click="goto('unique')">Unique Evolution</b-nav-item>
            </b-nav>
          </b-card>
        </div>
      </b-col>
      <b-col>
        <h2>Human Aging Model Systems</h2>

        <blockquote>
          <p align="justify">I want to know <router-link to="/ageing-theories">why we, humans, age</router-link> and how we can fight and ultimately <router-link to="/ageing-cure">cure human aging</router-link>. The goal of biomedical research is to improve the human condition and great emphasis is placed on translating findings into human applications. As such, <router-link to="/gerontology">gerontology</router-link> must be more than curiosity-driven, even though the use of model organisms is inevitable. In this essay, I present the different model systems used to study human aging and debate their strengths and pitfalls.</p>

          <p><em>Keywords:</em> ageing, biogerontology, insects, Homo sapiens, non-human primates, translational science, vertebrates</p></blockquote>

        <hr width="80%" size="1">

        <p align="justify">One major difficulty in studying human aging is its duration, particularly because researchers themselves are aging and have a limited lifespan. Because researchers cannot conduct experiments in humans in the same way drugs aimed at cancer or AIDS can be tested in clinical trials, most biogerontologists resort to model systems and then extrapolate data from these different models into humans. The choice of models, however, is diverse and highly controversial (Gershon and Gershon, 2000b; Partridge and Gems, 2007). The major model systems used to study human aging are: 1) human cells; 2) unicellular organisms such as the yeast <em><router-link to="http://genomics.senescence.info/species/entry.php?species=Saccharomyces_cerevisiae">Saccharomyces cerevisiae</router-link></em>; 3) the roundworm <em><router-link to="http://genomics.senescence.info/species/entry.php?species=Caenorhabditis_elegans">Caenorhabditis elegans</router-link></em> 4) the fruit fly <em><router-link to="http://genomics.senescence.info/species/entry.php?species=Drosophila_melanogaster">Drosophila melanogaster</router-link></em> 5) rodents such as mice (<router-link to="http://genomics.senescence.info/species/entry.php?species=Mus_musculus"><em>Mus musculus</em></router-link>) and rats (<router-link to="http://genomics.senescence.info/species/entry.php?species=Rattus_norvegicus"><em>Rattus norvegicus</em></router-link>). The small size and short life cycles of these organisms--even mice do not commonly live more than 4 years--make them inexpensive subjects for aging studies, and the ability to genetically manipulate them gives researchers ample opportunities to test their <router-link to="/ageing-theories">theories</router-link> and unravel molecular and genetic mechanisms of aging. Nonetheless, the employment of inadequate models to study human aging can be catastrophic for research since it can shift the focus of gerontology to pathways that, even though relevant in a certain model, may be irrelevant in humans. </P>

        <blockquote><H2>Studying Human Aging in Humans</H2></blockquote>

        <p align="justify">Because the human aging process takes decades to develop it is virtually impossible to study it in vivo. Researchers can describe human aging and investigate age-related pathologies, as <router-link to="/ageing-definition">mentioned before</router-link>. Longitudinal studies follow individuals throughout their lives while cross-sectional studies compare young and old individuals. Both types of studies are observational, not mechanistic. There are also genetic studies of longevity in humans (Puca et al., 2001; Perls et al., 2002; Perls, 2006), but as <router-link to="/ageing-definition">detailed elsewhere</router-link> longevity is only a proxy for aging and the true relevance of these studies to understand the human aging process remains to be established.</P>

        <p align="justify">One major model system of human aging are human cells, which have as major advantage the fact that researchers can concentrate on human biology. It is reasonable to assume that human aging has a cellular basis (de Magalhaes, 2004; de Magalhaes and Faragher, 2008). Nonetheless, cellular models and the methods used to study them have several caveats, and so in vitro results may not be representative of what happens in vivo (Mondello et al., 1999). Succinctly, the major argument against cellular models is that most cellular models of aging, such as <router-link to="/cell-ageing">replicative senescence</router-link>, are based on measurements of cell proliferation which are not necessarily a measurement of vitality (Cristofalo, 2001). Cancer, for instance, is derived from rapid, uncontrolled cellular proliferation. Other methods exist to measure aging in cells, such as stress resistance, but the relevance of these methods to organismal aging remains to be demonstrated (de Magalhaes, 2004). Cellular models of aging will not be covered in detail here as they are discussed in detail in <router-link to="/ageing-cure">another essay</router-link>.</P>

        <blockquote><H2>Studying Human Aging in Model Organisms</H2></blockquote>

        <p align="justify">Human studies should always be preferred, but model organisms are simply unavoidable in gerontology. Much of what we know about aging today derives from organisms like yeast, mice, rats, fruit flies, and roundworms (Fig. 1). These traditional biomedical model organisms benefit from having widespread resources, reagents and protocols that allow studies to be conducted in a faster and cheaper way. Scientifically, there are also advantages, such as the possibility of employing large-scale genetic screens and functional genomics (for a review de Magalhaes, 2009), that are not possible in humans or in other non-traditional model organisms. To give an example, thousands of genes (Hamilton et al., 2005) and drugs (Petrascheck et al., 2007) can be screened for effects on worm lifespan, so lower model organisms are adequate for initial surveys.</P>

        <p align="justify">The downside of model organisms, of course, is that it is nearly impossible to tell whether an organism is representative of human aging or not. It has been argued that similar mechanisms operate across many species (Longo, 1999; Longo and Fabrizio, 2002), while others have proposed that some aging mechanisms (called &quot;public&quot;) are common to all species while others are unique (&quot;private&quot;) of each species (Martin et al., 1996). Since the basic blocks of life are common to most known species, common pathways might be involved in aging across phylogeny (Tissenbaum and Guarente, 2002). Could it be that the weakest pathway succumbing to senescence is the same in all organisms? Such hypothesis is hard to believe based on the huge diversity of aging phenotypes found in <router-link to="/ageing-animals">Nature</router-link>, and certain animals appear to age for different causes than us. For example, the male Australian mouse (<em>Antechinus stuartii</em>) has a bizarre aging phenotype, as mentioned <router-link to="/ageing-animals">elsewhere</router-link>. The rapid death following reproduction observed in <em>Antechinus</em> and in other species is much different from the gradual waning of humans and so <em>Antechinus</em> is not a good model of human aging as different mechanisms are likely involved. The traditional biomedical model organisms (Fig. 1) all exhibit a gradual decline but the question remains of whether they are accurate paradigms of human aging.</P>

        <div align="center"><p><img src="models_aging.jpg" alt="Model organisms" width="277" height="228" border="0"></p></div>

        <blockquote>
          <p align="justify"><strong>Figure 1:</strong> Major model organisms of aging: yeast (top left), roundworms (top right), fruit flies (bottom left), and mice (bottom, right). The picture of <em>C. elegans</em> is used with permission from the copyright holders Juergen Berger and Ralf Sommer, Max-Planck-Institute for Developmental Biology, Tubingen, Germany. The picture of a fruit fly was taken by Andre Karwath and the picture of <em>S. cerevisiae</em> was taken by Maxim Zakhartsev and Doris Petroi, International University Bremen, Germany.</P></blockquote>

        <p align="justify">Even in animals that age gradually there is no <em>a priori</em> reason to expect them to age for the same causes and mechanisms as humans (Gershon and Gershon, 2000a). One problem is that all models organisms are considerably shorter-lived than humans and were developed for laboratory research based on their high fertility. Not only this means that different evolutionary processes acted on these organisms and on humans (see Austad, 1997b for arguments), but selection for fertility may have also selected for short lifespans in laboratory strains that generate biases in aging studies. In other words, it has been argued that the life-extending gene variants found in these organisms may  be simply restoring lifespan to what is normally found in the wild (Spencer and Promislow, 2002b). The fact that wild-derived mouse strains take longer to reach sexual maturity and live significantly longer than common laboratory strains supports this view (Miller et al., 2002b). On the other hand, worm strains (N2) seem to have been adapted to lab conditions (Chen et al., 2006), yet even wild-derived nematodes are long-lived under <router-link to="/caloric-restriction">CR</router-link> (Sutphin and Kaeberlein, 2008). Interestingly, CR extends the maximum lifespan of wild-derived mice but not average lifespan, suggesting that genotype impacts on CR effects (Harper et al., 2006). A related problem is that laboratory strains are often genetically homogeneous, which provides more consistent results, but also gives rise to discrepancies between strains on the effects of genes or interventions on aging (Partridge and Gems, 2007; de Magalhaes, 2014b).</P>

        <p align="justify">Human physiology can be much different than that of model organisms. Clearly, the phenotypes of aging in yeast and humans are totally unalike (Gershon and Gershon, 2000b). Not even researchers working on yeast expect yeast aging to be a perfect mirror of human aging (Sinclair, 2002; Jazwinski, 2005), and some of the same criticisms aimed above at human cells can be extrapolated to yeast. <em>Drosophila</em> and <em>C. elegans</em> are mostly composed of post-mitotic cells, which means that not only they do not normally have cancer or many other age-related diseases, but it raises doubts on how valid results obtained in these animals are when extrapolated to humans. It is possible that some general pathways of aging are conserved between all organisms, as discussed below, but certainly not all age-related changes overlap. At present, it is impossible to tell for sure if a given model organism is accurate or how accurate it is. It does appear reasonable to assume that species evolutionary closer to humans, such as mice, have higher chances of being representative of human biology than evolutionary distant species such as yeast.</P>

        <p align="justify">It can be argued that even if the aging process is not the same in distant organisms and humans, studies in lower life forms can help us understand the dynamics and structure of human aging. If aging is the corruption of life, then understanding how life itself works may help us understand aging. Much of what we know about the biochemistry of life--e.g., DNA replication and repair--came from studies in lower life forms such as bacteria and yeast. Hundreds of <router-link to="/genetics-of-ageing">genes that modulate aging</router-link> have been identified in model organisms (de Magalhaes et al., 2009a), such as in yeast (Jazwinski, 2001), <em>C. elegans</em> (Johnson, 2002), <em>Drosophila</em> (Tower, 2000), and mice (Liang et al., 2003; Hasty and Vijg, 2004). These findings can serve as the basis for research into mammals and humans (Sinclair, 2002; Tissenbaum and Guarente, 2002; Butler et al., 2003; Warner, 2003; Liu et al., 2005). Some of these findings, such as <router-link to="/caloric-restriction">CR</router-link> and the insulin-signalling pathway (Longo and Fabrizio, 2002; Butler et al., 2003), appear to be conserved between different species while others have not been demonstrated in mammals (see below). Therefore, some genes and mechanisms of aging found in model organisms may turn out to be relevant to humans, though studies on the mechanisms of aging in lower life forms must be corroborated in mammalian models before extrapolating into human aging. For example, some pathways and genes may be conserved between invertebrates and humans, but functions may be different and the higher complexity of mammals means that even if functions are conserved human pathways will have unique features not present in lower life forms. Gene expression analyses of longevity-assurance mechanisms in flies, worms and mice reveal some, yet few, overlapping pathways (McElwee et al., 2007). Similarities in pathways related to aging in  different organisms could also be due to similar selection processes that derive  from domestication (Reznick, 2005). Clearly, explaining human aging based on research in model organisms, even mice, is problematic.</P>

        <p align="justify">The telomeres, described in more detail <router-link to="/telomeres-telomerase">elsewhere</router-link>, are the perfect example of the limitations of model systems in aging research. Clearly, they are major players in <router-link to="/cell-ageing">cellular senescence</router-link> in human cells as well as other organisms. Telomere dysfunction in <em>S. cerevisiae</em> due to mutations in <router-link to="/telomeres-telomerase">telomerase</router-link>, an enzyme critical for telomere maintenance, leads to senescence (Lundblad and Szostak, 1989; Lowell and Pillus, 1998). In <em>C. elegans</em>, telomerase defects appear to result in sterility after a certain number of generations (Ahmed and Hodgkin, 2000), but a role of telomeres in its aging process has not been established. In <em>Drosophila</em>, telomere maintenance does not appear to involve telomerase, though other proteins involved in telomere maintenance may overlap with those of humans (Cenci et al., 2005). Telomerase-deficient mice are normal up to four generations and then show some signs of accelerated aging (Blasco et al., 1997; Rudolph et al., 1999), but telomerase overexpression does not alter aging in mice (Artandi et al., 2002). On the other hand, telomerase dysfunction in humans causes a disease called dyskeratosis congenita, which shares some features with the sixth generation telomerase-deficient mice (Marrone and Mason, 2003). It is therefore nearly impossible to determine the impact of the telomeres and telomerase in human aging based on model systems. Even between mice and humans, there are similarities but also differences in the biological outcomes of telomerase deficiency.</P>

        <p align="justify">Although aging in different mammals is often phenotypically similar, as <router-link to="/ageing-animals">mentioned before</router-link>, even eutherians may have different mechanisms of aging. As argued by others (Reznick, 2005), candidate genes emerging from a given model organism are an answer, not the one and only answer. Nonetheless, the bulk of research in mammals is based in short-lived animals like mice and rats whose evolutionary forces acting on aging may have been different from those acting in humans (Austad, 1997b). Besides, there are numerous examples of research in animals, including mammals, being inadequate to humans (Pound et al., 2004). The phenotypic differences mentioned above between mice and humans due to telomerase deficiency are a perfect example. As proven time and time again in other biomedical fields, what occurs in the aging process of other mammals may not be representative of human biology (reviewed in Davenport, 2003). Therefore, if we base our understanding of human aging on model organisms, even mammalian models, we must be careful about extrapolating findings to humans. </P>

        <p align="justify">Unfortunately, there is no simple solution to the issues mentioned above. <router-link to="/gerontology">Gerontology</router-link> continues to be dependent on model systems. While these have provided--and will continue to provide--clues regarding mechanisms of aging and even targets for drug discovery with potential human applications (reviewed in de Magalhaes et al., 2012), findings from model organisms must be interpreted with caution. One of the reasons why the mechanisms responsible for human aging remain largely a mystery is the lack of unambiguous models where scientists can test their hypotheses and the controversy relating to the interpretation of findings in current model organisms.</P>

        <blockquote><H2>Underrated Models of Aging: Reptiles, Naked Mole-Rats and Whales</H2></blockquote>

        <p align="justify">One of the problems of research on aging is that it is based on only a handful of models. Definitely, more models of aging would be invaluable to gerontology, particularly models biologically closer to humans. For example, employing other primate models in the study of aging could open new opportunities for research on aging because we are biologically closer to them; some primate species, such as marmosets, have been shown to age considerably faster than humans (Austad, 1997c; Tardif et al., 2011). It is not simple, however, to develop new models for studying aging or new biomedical models for that matter. As mentioned above, a variety of resources such as protocols and reagents are available for traditional biomedical models and developing such resources for a new model organism costs time and money. It would be worthwhile investment, though, and marmosets for instance are being developed as a model for aging (Tardif et al., 2011).</P>

        <p align="justify"><router-link to="/evolution-of-ageing">Previously</router-link>, I argued that reptiles, in general, age slower than mammals. Not only reptiles age slower than size-equivalent mammals, but several reptilian families feature apparently non-aging animals with traits associated with long lifespans such as continuous tooth replacement. As such, it is possible that mammals lack certain anti-aging mechanisms that are present in some or all reptiles (de Magalhaes and Toussaint, 2002). A few studies in reptiles have already began to explore mechanisms that may contribute to the delayed reptilian aging (see Lutz et al., 2003). For instance, neurogenesis is predominant in reptiles (Font et al., 2001). Other studies found unique traits in reptiles that could be useful to humans: crocodiles have been shown to possess novel antimicrobial peptides (Shaharabany et al., 1999). Clearly, long-lived reptiles are an underestimated model for the study of aging and more attention should be given to study reptilian aging or the apparent absence of aging of some species.</P>

        <p align="justify">Other <router-link to="http://genomics.senescence.info/species/query.php?show=1&sort=4&page=1">long-lived animals</router-link> could be extremely useful models of aging not so much to discover what causes aging but to investigate how we can fight it. In other words, traditional biomedical models provide clues about the mechanisms of aging and disease, yet an unexplored paradigm in biomedical research is the use of disease-resistant organisms to identify genes, mechanisms  and processes that protect against disease. As <router-link to="/ageing-animals">mentioned before</router-link>, some amphibians and fishes also feature negligible senescence (reviewed in Finch, 1990; Cailliet et al., 2001). Since amphibians and fishes are evolutionary further from us than reptiles, they are not, <em>a priori</em>, better models but can still prove useful. For example, amphibians can regenerate entire limbs while mammalian tissues, such as muscle, can only regenerate as isolated entities (reviewed in Brockes et al., 2001; Carlson, 2003). Lastly, birds too have been proposed as potentially useful models for understanding human aging due to their slow aging rates when compared to size-equivalent mammals (Holmes and Austad, 1995; Holmes et al., 2001). With the emerging age of genomics, employing these long-lived species in studies of aging is becoming a reality (de Magalhaes et al., 2010), for example via bioinformatics analyses (de Magalhaes and Toussaint, 2004b).</P>
        <p align="justify">Long-lived mammals, although none avoid aging completely, may also prove extremely useful to unravel the mechanisms of longevity and healthy aging. In 2007, myself and others proposed the sequencing of long-lived  mammals and specifically of the naked mole-rat (<em>Heterocephalus glaber</em>), the white-face capuchin monkey (<em>Cebus capucinus</em>) and the bowhead whale (<em>Balaena mysticetus</em>) (de Magalhaes et al., 2007b). Genome and RNA sequencing of the naked mole-rat has since revealed insights and candidate genes regarding the evolution of longevity (Kim et al., 2011; Yu et al., 2011). In particular, it appears that genes associated with oxidoreduction and mitochondria are expressed at higher levels in the naked mole-rat which might contribute to their long lifespan (Yu et al., 2011). Naked mole-rats also exhibit an extraordinary resistance to cancer (Buffenstein, 2008), and studies are beginning to unravel the anti-tumour mechanisms of  naked mole-rat cells (Seluanov et al., 2009). For example, they are more resistant to experimental tumorigenesis  with oncogenes (Liang et al., 2010). As the <router-link to="/ageing-animals">longest-lived mammal</router-link>, bowhead whales are equally fascinating and, because of their massive size, whales must have evolved anti-tumor mechanisms not present in humans (reviewed in Caulin and Maley, 2011).  Though for obvious reasons not easy to study experimentally, bioinformatics and genomics can provide clues about the genetic and molecular mechanisms that allow whales to live longer than humans and resist cancer (de Magalhaes et al., 2007b). Cellular studies could also be useful for studying long-lived species whose study as organisms would be practically impossible (Austad, 2001).</P>

        <p align="justify">It may be asked: why learn from species that are behind us in the race for immortality? It has been proposed that species without detectable senescence can "teach" us much more than species with short lifespans (Strehler, 1986). Even in species such as whales, elephants or naked mole-rats their evolution of longevity might have followed different pathways than in humans; studies in these species can lead to the discovery of new ways to combat against age-related diseases and, crucially, in the fight against aging itself, the only disease we all suffer from. The current explosion in genomics also makes large-scale studies possible, including in <router-link to="/comparative-biology">comparative genomics</router-link>. Research on several of these species can then allow hypothesis to be tested in traditional model systems, for example by creating cell lines or mice with genes from long-lived species that if successful can then be extrapolated to humans. Ultimately, animal models of resistance to disease and aging may prove valuable for human disease  prevention and aging retardation.</P>


      </b-col>

    </b-row>


  </b-container>


</template>
<script>
import Footer from "./AppFooter";

export default {
  components: {Footer},
  methods: {
    goto(refName) {
      var element = this.$refs[refName];
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
};
</script>
<style>
h2 {
  padding-top: 30px;
}

.sidebar {
  position: -webkit-sticky;
  position: sticky;
  top: 3%;
}

</style>
