<!--TODO: Make left nav float-->
<template>
  <b-container fluid="sm">
    <b-row class="text-left">
      <b-col cols="2">
        <div class="sidebar">
          <b-card>
            <b-nav vertical>
              <b-nav-item @click="goto('fear')">What Is Aging?</b-nav-item>
              <b-nav-item @click="goto('dem')">Demographic Measurements</b-nav-item>
              <b-nav-item @click="goto('path')">Pathological and Physiological Age-Related Changes</b-nav-item>
              <b-nav-item @click="goto('basic')">Basic Definitions in Gerontology</b-nav-item>
            </b-nav>
          </b-card>
        </div>
      </b-col>
      <b-col>
        <h2>Some Animals Age, Others May Not</h2>

        <blockquote>
          <p align="justify"><router-link to="/ageing-definition">Previously</router-link>, I described the major features of the human aging process. In the amazing biodiversity of our planet, however, we can find diverse forms of aging, many of which are fascinating. In this essay I describe the aging phenotypes observed in an array of species and how these compare to human aging. By studying the aging process of other animals and comparing the way different species age, it may be possible to gather clues about the human aging process and how to delay it, as further <router-link to="/ageing-cure">detailed elsewhere</router-link>.</P>

          <p><em>Keywords:</em> ageing, biogerontology, comparative biology, immortal germplasm, life span, microbes, nature, phylogeny, vertebrates</p></blockquote>

        <hr width="80%" size="1">

        <p align="justify">This essay follows a phylogenetic perspective, starting in the species most distant from us (Figure 1). As the we move to species evolutionary and biologically closer to us, I increase the detail in which I describe them. Many of the species mentioned in this essay are present in our lab's <router-link to="/ageing-cure">AnAge database</router-link>, the benchmark aging and longevity database in animals (de Magalhaes and Costa, 2009), and further information and quantitative data on the species mentioned below is likely available.</p>

        <pre>
          +---- Eubacteria
          |
 Life ----|
          |    +---- Archaea
          |    |
          +----|
               |                         +---- Metazoa (Animals)
               |                         |
               |                    +----|
               |                    |    |
               +---- Eukaryotes ----+    +---- Fungi
                                    |
                                    |
                                    +---- Plants and Protozoa
</pre>

        <blockquote>
          <p align="justify"><strong>Figure 1:</strong> Simplified tree of the evolution of life on earth. (Adapted from Maddison and Schulz, 2004.)</P></blockquote>

        <blockquote><H2>Primordial Life Forms</H2></blockquote>

        <p align="justify">The species further from us are prokaryotic microorganisms (Maddison and Schulz, 2004). Bacteria, for instance, are unicellular organisms that reproduce by cell division or fission; normally a mother cell divides into two equal daughter cells (Brock, 1997). Since we cannot distinguish between progenitor and offspring it was thought that these organisms do not age. Protected from violent death, bacteria have until recently been thought to be immortal. However, senescence has been reported in a bacterium with asymmetric division, <em>Caulobacter crescentus</em>, in the form of a decrease in reproductive output with age (Ackermann et al., 2003). <em>Escherichia coli</em> cells growth-arrested by nutrient depletion have also been studied in the context of aging since they lose their ability to recover and reproduce (reviewed in Nystrom, 2002). Evidence that division in <em>E. coli</em> is functionally asymmetrical has been suggested as evidence of aging in this species. Briefly, <em>E. coli</em> divides in the form of a rod and the cell that inherits the oldest end, or pole, exhibits a diminished growth rate, decreased offspring production, and an increased incidence of death (Stewart et al., 2005). On the other hand, certain bacteria can form spores and remain in a state of suspended animation for years with one study reporting the growth of a bacterium with 250 million years (Vreeland et al., 2000). Nevertheless, and despite the basic cellular functions being the same for all living organisms, bacteria's constitution and physiology have many differences when compared to human cells--e.g., bacteria have circular chromosomes, do not have mitochondria, etc. So while these observations are intellectually stimulating, their relevance to understanding human aging is somewhat dubious.</p>

        <p align="justify">When observing eukaryotic species we start to witness sex and its implications: sexual genetic recombination can be seen as a re-adaptation of the genome to the environment with the exchange of genetic information being advantageous in terms of increasing diversity. Sex also appears to be related to the emergence of aging in many evolutionary lineages. Beginning with ciliates, species exist in which individual cells are "destined to die," a process resembling the programmed death of the organism that we will also witness ahead in animals. An example is the protozoan <i>Tokophrya</i> (Karakashian et al., 1984): it reproduces by internal "budding," an asymmetric mitotic division, yet it is born without any means to dispose of wastes, which makes individual death inevitable. This form of aging resulting from mechanical limitations in the design of organisms has be called "mechanical senescence" (Comfort, 1964). In addition, asexually reproducing clones show another form of aging, called clonal or replicative senescence in that they stop proliferating; interestingly, cells born from older individuals have shorter lifespans. <i>Paramecium</i> and <i>Tetrahymena</i> are two other well-studied species in gerontology (Nanney, 1974). They can reproduce asexually for hundreds of generations but eventually reach clonal extinction--though perhaps not all strains in the case of <i>Tetrahymena</i>. In <i>Paramecium</i> it has been demonstrated that sex--the two cells fuse, exchange genetic material and then segregate--can rejuvenate individual cells (Smith-Sonneborn, 1987; Bell, 1988). Finally, numerous species among ciliates and other protista show no evidence of aging or clonal senescence; examples are found among the taxa Amoebina, Cryptomonadina, Phytomonadina, Sarcosporidia, and Radiolaria (Finch, 1990, p. 228). Lacking a sexual phase many species can proliferate with no detectable clonal senescence.</p>

        <blockquote><H2>Plants (kingdom: Plantae)</H2></blockquote>

        <p align="justify">Defining when life begins and ends is quite easy for us humans. Life begins at birth--or at conception or when the central nervous system is formed--and ends at brain death. But when life and individuality begin in other kingdoms is harder to define. When I was younger, and still had free time, I sometimes did gardening with my mother. As many are aware, for many species of plants if you cut a graft, put it in water, and then plant it in the soil, you will have a new plant. Similarly, there are species in the plant kingdom (Plantae) in which trees are generated on the roots of another tree. If we have two trees connected by the roots in which one of the trees originated from the roots of another, is this the same tree or are there two trees? And when the first tree dies, is the second tree now another tree or is it still the same tree? Aging in plants is thus difficult to define. This process of vegetative reproduction can, in some species, be done (in theory) eternally; grafting is widely used is agriculture and many species--tulips (<i>Tulipa clusiana</i>), saffron crocus (<i>Crocus sativa</i>), and banana (<i>Musa sapientum</i>)--are examples of how it can be done for hundreds if not thousands of years (Cook, 1983; Finch, 1990, p. 229). Cases of species undergoing clonal reproduction for over 10,000 years have been reported with one species (<em>Lomatia tasmanica</em>) dated to be at least 43,600 years (reviewed in Munne-Bosch, 2008). Species exist, however, in which vegetative reproduction shows decreasing vigor with time. For example sugarcane and citrus show limited clonality in cuttings but other factors besides aging, such as viruses, can be involved (Finch, 1990, p. 230).</p>

        <p align="justify">Another unique feature of plants is that, in general and unlike animals, they segregate their germ cells from the soma shortly before reproduction. In addition, there is an enormous diversity of plants and many seem capable of living thousands of years. Asexual, agametic reproduction is highly spread among higher and lower plants (Watkinson and White, 1985). Examples include the genera <i>Rubis</i>, <i>Hieracium</i>, <i>Poa</i>, and <i>Taraxacum</i> (Cook, 1983).</p>

        <p align="justify">There are also many plant species that show clear signs of senescence. Some, such as bamboo, reproduce, age, and die at well defined times indicating a pre-programmed mechanism. Bamboo are then considered semelparous, meaning they reproduce only once, in contrast to iteroparous species like humans that can reproduce more than once during their lifetime. Also note that semelparous species can be long-lived. For example, plants of the genus <i>Agave</i> can take 100 years to mature and then suddenly die, which can also be called "big bang" reproduction (Finch, 1990, p. 101). These events are hormonally triggered and, for example, depending on the species of bamboo can take between 7 and 120 years (Janzen, 1976). Many species of plants also show a functional decline with time, indicating a slow aging rate. Examples are well known in agriculture such as apple, orange, and other fruit trees. In some cases, such as in citrus, vegetative reproduction by cutting can lead to a sort of rejuvenation (Finch, 1990, p. 127). Our knowledge of how hormones control these events is limited but it can be that the hormones produced by roots or growing tips influence the process.</p>

        <p align="justify">Finally, probably the best described example of a non-aging plant is the bristlecone pine. This tree grows on high rocky ground practically without predators and has been estimated to live up to 4,713 years. Studies have shown an absence of MRDT and no declines in reproductive output with age (Lanner and Connor, 2001).</P>

        <blockquote><H2>Fungus (kingdom: Fungi)</H2></blockquote>

        <p align="justify"><i>Saccharomyces cerevisiae</i> is a yeast that reproduces by budding divisions (Jazwinski, 1990). A new cell forms as a small outgrowth of the mother cell, the bud enlarges and then separates, leaving a scar behind. Since each cell can only do this process a limited number of times it has been argued that this is a form of aging. In addition, chronological lifespan can also be quantified and used as an estimate of aging. <router-link to="/ageing-models">A favorite model of researchers</router-link>, the "aging process" of this yeast has been studied in detail. One possible cause of senescence might be ribosomal DNA circles (Sinclair and Guarente, 1997; Sinclair, 2002). Around the middle of the lifespan a circular copy of the rDNA pops out of the genome and begins replicating, eventually leading to the mother cell's death. Since daughter cells are born without this rDNA, perhaps that is what makes them young. An alternative hypothesis is a role of the mitochondrion, the cell's powerhouse, in the aging of <i>S. cerevisiae</i> (Jazwinski, 2005). Another yeast, <i>S. pombe</i>, reproduces by fission but it shows asymmetrical cell division and replicative senescence (Barker and Walmsley, 1999). <i>Pseudospora</i> is a filamentous ascomycete that has also been the subject of gerontological research. Its lifespan is limited and, although the mechanism has not yet been fully elucidated, it can involve a process involving copper levels that in turn impact on the energy transduction apparatus of mitochondria as well as reactive oxygen species production (Osiewacz and Borghouts, 2000). Probably the oldest known fungus is the <i>Armillaria ostoyae</i>. Some authors believe a giant fungus of this species at the Malheur National Forest (US) can be over 2,400 years and is the biggest organism on earth (Ferguson et al., 2003).</P>

        <blockquote><H2>Animals (kingdom: Animalia or Metazoa)</H2></blockquote>

        <p align="justify">Like in plants, vegetative propagation may occur among some animals, although usually coupled with sexual reproduction. <i>Campanularia</i> reproducing asexually have been claimed not to age despite showing a cycle of growth and involution (Brock and Strehler, 1963). <i>Hydra</i> and <i>Cyanea capillata</i> have also been claimed by some authors not to show senescence (Brock and Strehler, 1963; Martinez, 1998), despite contrasting opinions of others (Bell, 1988). Sponges and corals are other good examples of asexual vegetative reproduction leading to long lifespans--over 200 years in the case of corals and perhaps thousands of years in the case of sponges. Some evidence, however, supports the idea that corals age (Finch, 1990, p. 233). Still, corals have high infant mortality rates and maybe a decrease in mortality with age, which makes them a fascinating case (Finch, 1990, p. 242).</p>

        <p align="justify">Worms vary much between asexually and sexually reproducing species and many species have alternating cycles of both--like in certain plants, a process often dependent on diet and temperature. One flatworm, <i>Stenostomum tenuicauda</i>, produced a calculated number of 1,000 asexual generations for 11 years and <i>Ctenodrilus monostylos</i> was kept reproducing by fission for 60 years. Asexually reproducing parasitic worms must have reproduced asexually for decades (Moore, 1981; Finch, 1990, p. 235). Finally, protochordates also reproduce asexually. Ascidians reproduce by fission or budding on a regular basis. For example, in <i>Perophora viridis</i> buds originate in certain lymphocytes that are, in effect, stem cells capable of creating a full organism with heart, neural structures, etc. (Finch, 1990, p. 236).</p>

        <p align="justify">One of the most widely studied species in the world is the soil nematode <i>Caernohabditis elegans</i>, composed mostly of post-mitotic cells (Murakami et al., 2000). This species has a very short lifespan--days to weeks--but it can be radically extended by making the animal enter an alternative developmental pathway called <i>dauer</i>. This pathway consists of a developmental arrest and is normally activated when animals are starved or under crowded conditions; it delays development leading to an increased adult phase (Klass and Hirsh, 1976). Certain <router-link to="/genetics-of-ageing">genetic interventions</router-link> can also induce this <em>dauer</em> phase. In fact, the first gene ever shown to retard aging (<em>age-1</em>) was identified in <i>C. elegans</i> (Johnson, 1990). It is interesting to note the contrast between the short-lived <i>C. elegans</i> and other parasitic worms like <em>Necator americanus</em> and <em>Ancylostoma duodenale</em> that can live up to 15 years (Finch, 1990, pp. 215-216). Another nematode worm, <em>Strongyloides ratti</em>, has both a short-lived free-living (~5 days) form and a parasitic form that can live over one year inside a host (Gardner et al., 2006). While these differences in lifespan are dramatic, I should note that the two forms are quite different morphologically and physiologically. The ability of a single genome to give rise to two or more morphologies is called polyphenism.</p>

        <p align="justify">Rotifers are minute aquatic multicellular organisms that have short lifespans ranging from a few days to months; males, unlike females, typically lack excretory systems and therefore have even shorter lifespans (Finch, 1990, p. 72). Again, this can be seen as a form of mechanical senescence.</P>

        <p align="justify">One of the animal species with the longest longevity is an invertebrate tubeworm called <i>Lamellibrachia</i>. In contrast to the rapid growth and much shorter lifespans of similar species living in habitats richer in nutrients, animals living around hydrocarbon seeps grow very slowly and have longevities estimated to be between 170 and 250 years (Bergquist et al., 2000). Other long-lived invertebrate species include the bivalve mollusk ocean quahog (<em>Arctica islandica</em>) that has been estimated to live up to 400 years (Abele et al., 2008), and the red sea urchin (<em>Strongylocentrotus franciscanus</em>; Fig. 2) that may live up to 200 years (Ebert and Southon, 2003). These three species appear not to age and are referred to as species with negligible senescence (Finch, 1990). The <router-link to="http://genomics.senescence.info/species/">AnAge database</router-link> includes a list of the <router-link to="http://genomics.senescence.info/species/query.php?show=1&sort=4&page=1">longest-lived animals</router-link> and a list of <router-link to="http://genomics.senescence.info/species/nonaging.php">species with negligible senescence</router-link>.</p>

        <div align="center"><p><img src="../assets/sea_urchin.jpg" alt="Red sea urchin" width="316" height="252" border="1"></p></div>

        <blockquote><p align="justify"><strong>Figure 2:</strong> Red sea urchin (<em>Strongylocentrotus franciscanus</em>), which has been estimated to live up to 200 years and is considered a species with <router-link to="http://genomics.senescence.info/species/entry.php?species=Strongylocentrotus_franciscanus">negligible senescence</router-link>. Source: <router-link to="http://www.fws.gov">U.S. Fish and Wildlife Service</router-link>.</P></blockquote>

        <p align="justify">In general (but see below), insects are short-lived. Nonetheless, we find a staggering diversity of aging phenotypes among them. A common mechanical senescence process in insects involves aphagy (Weismann, 1891), or the inability to ingest a complete meal as an adult, generally related to defective mouthparts or a defective gut. Numerous examples exist among insects and include animals like mayflies and species in Ephemeroptera, Neoptera, Coleoptera, etc. (Finch, 1990, pp. 584-585). Many insects and other members of Arthropoda are therefore semelparous. Insects, of course, have a much different body plan than ours. For example, the fruit fly <i>Drosophila</i>, a common <router-link to="/ageing-models">model of aging</router-link>, is mostly composed of post-mitotic tissues and fragile organs, making it susceptible to wear and tear that affects irreplaceable organs and/or tissues.</p>

        <p align="justify">No mentioning of insects is complete without ants (Finch, 1990, pp. 67-72). Ants, like many other social insects such as honey bees, show polyphenism. Not only are ant castes morphologically different, but ants have two distinct aging phenotypes in workers and queens. What makes them fascinating is the fact that they all share the same genome and both are probably postmitotic, except perhaps the gut and sex cells. Queens can live over 15 years, 100 times more than the workers. The difference between workers and queens is that queens have specialized feeding; for example, larvae destined to become queens are fed ten times more often. In addition, queens suffer little mechanical abrasion and are constantly groomed by the workers. Also interesting are the large differences in lifespan between workers in the same colony depending on seasons. Hormonal levels dependant on the amount of activity needed by the colony appear to play a role in this. There are also exceptional cases of worker ants living over 5 years but these are rare. In fact, while workers show a clear acceleration of mortality, queens die very rapidly after their sperm stocks are exhausted, sometimes even assassinated by the workers. Therefore, queens may well feature negligible senescence.</P>

        <p align="justify">Apart from mechanical senescence, other processes can lead to rapid aging and/or sudden death after reproduction. Hormone-driven processes are common in many lower species. Some octopus species do not eat after spawning, which is driven by hormones (Wodinsky, 1977). Spiders such as <i>Frontinella pyramitela</i> have short lifespans and increased feeding leads to increased reproduction and earlier death (Austad, 1989). On the other end of the lifespan spectrum, female tarantulas can live more than 25 years without showing clear signs of aging (Finch, 1990, p. 78). Other arthropods with indefinite lifespan include lobsters, whose molting leads to the replacement of hard tissues avoiding wear and tear and leading to continual growth (Finch, 1990, p. 215). Among Echinodermata, sea urchins (as mentioned above) and other starfish are claimed to be able to live more than 40 years, showing decreasing mortality with size (Finch, 1990, p. 216). In mollusks, certain octopus species also show no signs of senescence (Arnold and Carlson, 1986).</p>

        <blockquote><H2>Chordates (phylum: Chordata)</H2></blockquote>

        <p align="justify">Moving closer to humans, tunicates are primitive aquatic animals, members of Urochordata. They have several asexual and sexual reproductive cycles and are typically short-lived (Finch, 1990, p. 236). On the other hand, hagfishes can show continued growth and very slow, if any, senescence as well as continued <i>de novo</i> oogenesis in adults; their estimated maximum lifespan is about 40 years (Finch, 1990, pp. 216-217). Despite many body plan similarities with hagfishes, lampreys are a completely different story. Lampreys are semelparous and show "big bang" reproduction followed by rapid senescence. In fact, adult lampreys typically do not eat and do not replace their oocytes.</p>

        <p align="justify">Jawed fishes are considered the most modern of fishes. Ray-finned fishes such as sturgeons can have very long lifespans, exceeding a century (Finch, 1990, pp. 216-217). Female sturgeons, however, may have a finite ovarian oocyte stock (Finch, 1990, pp. 134-135). Teleosts such as rockfishes also live very long, show no signs of reproductive senescence and grow continuously, albeit slowly (Fig. 3A). Some rockfishes, such as <em>Sebastes aleutianus</em> have been estimated to live over 200 years and show no signs of aging (Cailliet et al., 2001). Sharks are often claimed to show no senescence or cancer (Lane and Comac, 1992), but despite low cancer rates, cancer can appear and females may show reproductive senescence. On the other end of the spectrum, some fishes have very short lifespans. Certain annual African fishes such as of the genus <i>Nothobranchius</i> do not commonly live more than 12 weeks even in protected environments and exhibit signs of an extremely fast aging process (Valdesalici and Cellerino, 2003).</p>

        <div align="center"><p><img src="../assets/fishes.jpg" alt="Yellow rockfish and salmon" width="497" height="536" border="1"></p></div>

        <blockquote><p align="justify"><strong>Figure 3:</strong> Two fishes with completely different life-history strategies and aging phenotypes. A: Yellow rockfish (<em>Sebastes reedi</em>), which has been estimated to <router-link to="http://genomics.senescence.info/species/entry.php?species=Sebastes_reedi">live nearly a century</router-link>. B: Sockeye salmon (<em>Oncorhynchus nerka</em>), which <router-link to="http://genomics.senescence.info/species/entry.php?species=Oncorhynchus_nerka">dies shortly after spawning</router-link>. Source: <router-link to="http://www.fws.gov">U.S. Fish and Wildlife Service</router-link>.</P></blockquote>

        <p align="justify">A famous fish in gerontology is the salmon (Fig. 3B), a teleost, and its rapid senescence following reproduction is a landmark phenomenon. Typically salmon are born in rivers and lakes, migrate to the ocean until returning to spawn in fresh water and die shortly after. During the reproductive period, a hormonal cascade causes animals to stop eating, develop various pathologies, and eventually die (Finch, 1990, pp. 83-90). Castrated fish can live twice as long but eventually show the usual hormonal-based changes (Robertson, 1961). One fascinating facet of salmon senescence is that the salmon has a particular mussel parasite that can extend the salmon's lifespan by affecting the <router-link to="programmed_aging.html">hormonal program</router-link> of accelerated senescence (Ziuganov, 2005). Another remarkable observation is that in some normally semelparous species of salmon also exhibit iteroparous life histories; male jacks and parr mature early and parr can survive reproduction and mate again (Unwin et al., 1999).</P>

        <p align="justify">Certain salmoniforms show conditional semelparity. The steelhead trout <i>Oncorhynchus mykiss</i> is a good example; just like typical salmons, these animals have to spawn in rivers, but some animals are able to return to the sea and that way can survive to reproduce another year (Finch, 1990, p. 92). Another interesting case is the plaice (<em>Pleuronectes platessa</em>), a flounder-like fish; the female continually grows and shows no signs of aging while the male ages and dies (Bidder, 1932; Finch, 1990, p. 240). In fact, partly based on this species, Bidder proposed that cessation of growth leads to the onset of aging. Despite being true for many species, exceptions exist. A major open question is whether growth cessation is caused by hormonal changes or by intrinsic cellular limitations.</p>

        <p align="justify">Ending the marine examples I want to mention a phenomenon quite common among fishes, which is also observed in many invertebrates like certain insects, including <router-link to="/ageing-models">flies and worms</router-link> typically used in aging research. The walleye (<em>Sander vitreus</em>, formerly <em>Stizostedion vitreum</em>) is a fish found in North American freshwaters. Depending on the temperature of its environment, its lifespan can increase five-fold while also delaying maturation and overall development (Gosden, 1996, p. 107; Mangel and Abrahams, 2001). A delayed maturity and increased lifespan as a result of a lower ambient temperature is common in many ectotherms (see below).</P>

        <pre>
                      200 m.y.
                         +---- Mammals
                         |
                340 m.y. |
                   +-----|
                   |     |    +---- Turtles
                   |     |    |
                   |     +----|
Gnathostomata -----|          |     +---- Other Reptiles
                   |          +-----|
                   |                +---- Birds
                   |
                   +---- Amphibians
</pre>

        <blockquote>
          <p align="justify"><strong>Figure 4:</strong> Simplified tree of the evolution of mammals and closely related taxa. Most modern fishes are in Gnathostomata with the exception of sarcopterygian fishes, which are not shown. (Adapted from de Magalhaes and Toussaint, 2002; Maddison and Schulz, 2004.)</P></blockquote>

        <p align="justify">Approaching mammals (Fig. 4), amphibians have no reported cases of "big bang" reproduction, though some species are short-lived showing signs of gradual aging (Kara, 1994; Smirina, 1994). Overall, and although there are not many detailed studies of aging in amphibians, amphibians appear to be longer lived than mammals of the same size. In fact, aging's incidence and intensity appear to be lower in amphibians when compared to mammals (Finch, 1990, pp. 219-221; de Magalhaes and Toussaint, 2002). Studies in amphibians have reported possible negligible senescence in frogs (Brocas and Verzar, 1961; Plytycz et al., 1995a) and toads (Plytycz and Bigaj, 1993; Plytycz et al., 1995b), but this has not been proven. Like for many other species, temperature is a major factor in determining life history traits. Typically, animals in northern or mountain regions tend to live longer and, usually, mature later, though hibernation could be a factor too (Smirina, 1994). Reports of some age-related declines have been observed in small species such as frogs (Perez-Campo et al., 1993), <i>Rana temporaria</i> (Plytycz et al., 1995a), and the tiger salamander (Townes-Anderson et al., 1998). Other salamanders such as <i><em>Andrias</em> japonicus</i> live at least 55 years and show no reproductive senescence or decrease in fitness with age. Bullfrogs (<i>Rana catesbeiana</i>) show an increase in fitness with age as older females prefer older and larger males. The longevity record for the class belongs to the olm, a blind subterranean animal that has been predicted to live over 100 years and may be a case of negligible senescence (Voituron et al., 2011). A laboratory favorite is <i>Xenopus laevis</i>: it lives over 15 years and shows few signs of senescence. Oogonial proliferation in amphibians occurs after maturity but there are no reports at advanced ages. Nonetheless, it is possible that some amphibian species feature negligible senescence including neurogenesis and oogenesis in adulthood. Teeth in amphibians are polyphyodont, meaning animals develop several sets of teeth successively throughout life (reviewed in Kara, 1994).</p>

        <p align="justify">Like amphibians, reptiles not show "big bang" reproduction (reviewed in Patnaik, 1994), and tend to show a lower incidence and intensity of aging than most mammals (Finch, 1990, pp. 219-221; de Magalhaes and Toussaint, 2002). Some reptilian species show signs of aging comparable to what is observed in mammals (Majhi et al., 2000; Jena et al., 2002; Olsson and Shine, 2002). Unlike some animals, like many fishes, that grow continuously throughout their lives, reptiles tend to grow slower at older ages, in both short- and long-lived species. Like amphibians, most reptiles feature polyphyodonty (Patnaik, 1994). Several species of reptiles, particularly turtles, appear to feature negligible senescence and very long lifespans. Blanding's turtle (<em>Emydoidea blandingii</em>) has been shown to increase survival and reproductive output over a 75-year period (Congdon et al., 2001), and similar results have been reported for the eastern box turtle (<em>Terrapene carolina</em>; Fig. 5A; Miller, 2001). Marion's tortoise (<i>Geochelone gigantia</i>) is claimed to have lifespans over 150 years, which is uncertain but possible since some captive turtles live up to 70 years. An increase in mortality was found in wild <i>Geochelone</i> but extrinsic factors might be involved. The Galapagos tortoise (<em>Geochelone nigra</em>) also appears to be long-lived with a possible record longevity of 177 years (Fig. 5B). Some snakes might also escape senescence; many species actually lay more eggs as they increase in size with age; for instance, <i>Natrix maura</i> ceases to grow but animals can live beyond that point with no detectable increases in mortality. Despite some species having a sexual peak, reproductive senescence has not been convincingly reported in reptilians, though further studies are necessary. For example, alligators have been reported to exhibit some evidence of reproductive senescence but the results are inconclusive (Finch, 1990, pp. 144-145). Oogenesis in adulthood has been reported for some species yet again further studies of reproduction across the lifespan are necessary. Although the evidence is limited, it appears that reptilians and amphibians show a less intense aging phenotype than mammals with many species failing to show a characteristic maximum lifespan.</p>

        <div align="center"><p><img src="../assets/turtles.jpg" alt="Eastern box turtle and Galapagos tortoise" width="671" height="201" border="1"></p></div>

        <blockquote><p align="justify"><strong>Figure 5:</strong> Two examples of long-lived turtles that show no signs of aging. A: Eastern box turtle, which <router-link to="http://genomics.senescence.info/species/entry.php?species=Terrapene_carolina">can live up to 138 years</router-link>. B: Galapagos tortoise, which <router-link to="http://genomics.senescence.info/species/entry.php?species=Geochelone_nigra">can live up to 177 years</router-link>. Sources: Ryan Hagerty (A) and Paul Guther (B), <router-link to="http://www.fws.gov">U.S. Fish and Wildlife Service</router-link>.</P></blockquote>

        <p align="justify">Evolving, as mammals, from reptiles (Fig. 4), birds are another taxon whose aging phenotype is worth appreciating (Finch, 1990, pp. 144-150). Like amphibians and reptiles, birds are not known to exhibit rapid senescence or semelparity. Certain species show a definitive trend of accelerating mortality with age, being gallinaceous birds (order: Galliformes) the most extreme example (Ottinger, 2001). Other species, however, show very slow increases in mortality with age and some long-lived species show an increase in parenting success with age. Species with very long lifespans and little signs of reproductive senescence are common: the Andean condor (<i>Vultur gryphus</i>) is capable of living up to 75 years and is one the longest lived birds; no senescence has been reported but detailed studies are lacking. Other species such as <i>Fulmarus glacialis</i> and <i>Sterna paradisaea</i> also show little signs senescence (Gosden, 1996, pp. 55-56). From mathematical calculations it has been proposed that these long-lived birds must show some mortality increase, apart perhaps from condors. Parrots and cockatoos (order: Psittaciformes) are also known to be long-lived with anecdotal reports of animals living over 100 years, though detailed studies are lacking. Comparing birds with mammals, some authors suggest that birds age slower than mammals (Holmes and Austad, 1995; Holmes et al., 2001; Holmes and Ottinger, 2003). Nonetheless, there are no verified reports of birds with negligible senescence or animals living over 100 years. Birds do not have continuous growth.</P>

        <p align="justify">Before moving to mammals there is just one last group of species worth mentioning. These are species with a clearly defined finite lifespan but that might not age at all (Finch, 1990, pp. 222-226). Species with a very high IMR are expected to be short-lived, yet senescence might not necessarily occur. (A high extrinsic mortality--i.e., high IMR--is expected to lead to the <router-link to="/evolution-of-ageing">evolution of aging</router-link>, but this may not be an universal rule.) Exemplifying, in certain fishes, such as <i>Cynolebia</i> or <i>Nothobranchius</i>, adults die soon after spawning in the wild but their lifespan can be increased several fold in the laboratory where a gradual increase in mortality is witnessed. So, species might exist in which the high mortality masks an absence of senescence. <i>Chiton tuberculatus</i> is a marine mollusk that is an excellent case of what I call ecological senescence: at age four, animals show a large increase in mortality but this increase appears to derive from continual growth and the subsequent need to find new habitats where animals are more exposed to predation. Phenomena along these lines may cause increased mortality rates in other species with negligible senescence but continual growth. One last example is the saguaro cactus (<i>Cereus giganteus</i>); it shows a MRDT of 18 years but this is probably due to extrinsic factors such as accumulation of exogenous damage. Species showing no senescence and continuous growth might also be affected by ecological senescence; increasing size might lead, for example, to changes in diet that cause an increase in mortality.</P>

        <blockquote><H2>Mammals (class: Mammalia)</H2></blockquote>

        <p align="justify">One of the few reported mammalian species with "big bang" reproduction and semelparity is a marsupial called <I>Antechinus stuartii</I>, a type Australian mouse (Finch, 1990, pp. 95-98; Gosden, 1996, pp. 13-30). During the annual mating season, males become &quot;intoxicated&quot; with sex hormones. They have such an increased libido that they are unable to eat and eventually die of sexual stress. The endocrine changes even affect the immune system so that more energy is available for reproduction. Just like in the salmon, castrating the males also increases their lifespan by two to three-fold. Other small mammals such as the well-known lemmings also show seasonal population crashes or, as in voles (<i>Microtus townsendii</i>), high mortality in the spring, probably dependant on food resources yet these are not considered semelparous.</p>

        <p align="justify">Placental mammals, known as eutherians, show a large diversity in average and maximum lifespan (Finch, 1990, pp. 122-123). Some rodents, such as <i>Mus musculus</i> or <i>Rattus norvegicus</i> have short lifespans rarely exceeding 4 years. In contrast, the longest-lived rodent is the naked mole-rat with a record longevity of 28 years and is also fascinating in being exceptionally resistant to cancer (Buffenstein, 2005 & 2008). There are no recorded species of mammals with negligible senescence and it is unlikely that any exist. So far, all studied mammals featured reproductive senescence (Cohen, 2004), an increased mortality with age, and evidence of functional decline with age. The longest-lived mammal known is the bowhead whale; an individual with 211 years was reported in one study (George et al., 1999). Cetaceans, in general, appear to be long-lived with several anecdotal claims of animals living over 100 years. Elephants also show long lifespans and might live over 70 years (Finch, 1990, p. 152). Finally, bats are one interesting order of species (Chiroptera) for, despite their small size, they can live over 30 years and have a low MRDT (Fig. 6; Jurgens and Prothero, 1987; Austad and Fischer, 1991).</p>

        <div align="center"><p><img src="../assets/bat.jpg" alt="Little brown bat" width="458" height="189" border="1"></p></div>

        <blockquote><p align="justify"><strong>Figure 6:</strong> The little brown bat (<em>Myotis lucifugus</em>), despite its small size--they weight about 10 grams--can <router-link to="http://genomics.senescence.info/species/entry.php?species=Myotis_lucifugus">live up to 34 years</router-link>. Source: Don Pfritzer, <router-link to="http://www.fws.gov">U.S. Fish and Wildlife Service</router-link>.</P></blockquote>

        <p align="justify">Apart humans, other primates can be long-lived, though none are as long-lived as we are. Rhesus monkeys (<i>Macaca mulata</i>) can live over 35 years and 25/30 year-old animals tend to display the age-related patterns found in a 50/60 year-old human. Interestingly, rhesus monkeys have a MRDT similar, if not superior, to that of humans, showing that MRDT values are not perfect estimates of the rate of physiological aging. Chimpanzees (<em>Pan troglodytes</em>), our closest relatives, can live over 60 years and, although their aging process has not been studied in detail, they show age-related changes typical of humans at considerably earlier ages. Their MRDT is about 8 years, so is about the same as humans (Hill et al., 2001). It could be that chimpanzees age at the same pace as humans but the onset of aging occurs sooner in them (de Magalhaes, 2006). As for humans (<em>Homo sapiens</em>), our MRDT is about 8 years and our maximum lifespan is 122 years, as <router-link to="/ageing-definition">detailed elsewhere</router-link>. On the other hand, some primates can be shorter-lived and exhibit a fast rate of aging--though not as fast as rodents. These tend to be species more distant from humans, as primates biologically and evolutionary closer to humans tend to be long-lived since it is thought that longevity increased in the lineage leading to humans (Cutler, 1979). Examples of short-lived primates include marmosets (genus <em>Callithrix</em>), dwarf and mouse lemurs (genera <em>Cheirogaleus</em> and <em>Microcebus</em>), tarsiers (genus <em>Tarsius</em>), and animals of the Galagonidae family (Austad, 1997c). These animals tend not to live more than 20 years, show age-related changes in their second decade of life, and have short life cycles attaining sexual maturity in less than 2-3 years (Bons et al., 1992; Austad, 1997c; Harada et al., 1999).</P>

        <p align="justify">A well-documented mechanical senescence process in mammals is tooth erosion (Finch, 1990, pp. 196-202), which is a major problem for several species such as hippopotamus, horses, elephants, etc. Long-lived species evolved creative mechanisms to cope with this. For instance, elephants have up to six sets of molars. Still, and although the Nabarlek (<em>Petrogale concinna</em>) could be an exception, mammals are not known to be polyphyodont.</p>

        <p align="justify">One of the most interesting features of mammalian aging is that its phenotype is similar in most species (Finch, 1990, p. 619; Miller, 1999). Female reproductive senescence at mid-life, osteoporosis, arthritis, vascular lesions, cataracts, etc. are quite common among well-studied mammals. Despite some exceptions, such as certain marsupials like <em>Antechinus</em>, the pathophysiology of aging is remarkably similar in mammals which has implications for our understanding of genetic mechanisms of aging, as <router-link to="/genetics-of-ageing">discussed elsewhere</router-link>.</p>





      </b-col>
    </b-row>


  </b-container>

</template>


<script>
export default {
  name: 'Author',
  methods: {
    goto(refName) {
      var element = this.$refs[refName];
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
};
</script>



<style>
h2 {
  padding-top: 30px;
}

.sidebar {
  position: -webkit-sticky;
  position: sticky;
  top: 3%;
}

</style>

