<!--TODO: Make left nav float-->
<template>
  <b-container fluid="sm">
    <b-row class="text-left">
      <b-col class="text-left" cols="2">
        <div class="sidebar">
          <b-card>
            <b-nav vertical>
              <b-nav-item @click="goto('intro')">Introduction</b-nav-item>
              <b-nav-item @click="goto('hayflick')">The Hayflick Limit</b-nav-item>
              <b-nav-item @click="goto('biomarkers')">Biomarkers of Cell Senescence</b-nav-item>
              <b-nav-item @click="goto('stress')">Stress-Induced Premature Senescence</b-nav-item>
              <b-nav-item @click="goto('senesc')">Senescent Cells, Stress and Organismal Aging</b-nav-item>
              <b-nav-item @click="goto('stem')">Stem Cells and Germ Cells</b-nav-item>
            </b-nav>
          </b-card>
        </div>
      </b-col>
      <b-col>
        <div ref="intro">
        <h2>Cellular Senescence</h2>

        <blockquote>
          <p align="justify">Because cells are the fundamental building blocks of our bodies, it is logical to assume that cellular changes contribute to the aging process. In this essay I review the methods used to study cellular aging in vitro, in particular replicative senescence, and debate whether these findings could be related to organismal aging.</p>

          <p><em>Keywords:</em> ageing, cell immortality, cell immortalization, cellular immortality, cytogerontology, Hayflick phenomenon</p></blockquote>

        <hr width="80%" size="1">
        </div>
        <div ref="hayflick">
        <blockquote><H2>The Hayflick Limit</H2></blockquote>

        <p align="justify">In 1961, and in contradiction to what was thought at the time, Leonard Hayflick and Paul Moorhead discovered that human cells derived from embryonic tissues could only divide a finite number of times in culture (Hayflick and Moorhead, 1961). They divided the stages of cell culture into Phases I-III. Phase I is the primary culture, when cells from the explant multiply to cover the surface of the culture flask--most cell types grow in the lab attached to a solid surface. Phase II represents the period when cells divide in culture. Briefly, once cells cover a flask's surface, they stop multiplying. For cell growth to continue, the cells must be subcultivated. To do so, one removes the culture's medium and adds a digestive enzyme called trypsin that dissolves the substances binding cells together. After adding growth medium and pipetting one obtains the cells in a homogeneous suspension that are then divided by two--or more--new flasks. Cells then attach to the new flasks' surface and start dividing once again until a new subcultivation is required. Most cells divide vigorously and can often be subcultivated in a matter of a few days. After several months, however, cells start dividing slower, which marks the beginning of Phase III. Eventually cells stop dividing at all, though they may or may not die (reviewed in Hayflick, 1985 & 1994). Hayflick and Moorhead noticed that cultures stopped dividing after an average of 50 cumulative population doublings (CPDs)--splitting one flask of cells into two new flasks of the same size increases the CPDs by one, splitting by four flasks increases the CPDs by two and so on. This phenomenon of growth arrest after a period of apparently normal cell proliferation is known as the Hayflick limit, Phase III phenomenon, or, as it will be called herein, replicative senescence (RS).</p>

        <p align="justify">Hayflick and Moorhead worked with fibroblasts, a cell type found in connective tissue widely used in research, but RS has been found in other cell types: keratinocytes, endothelial cells, lymphocytes, adrenocortical cells, vascular smooth muscle cells, chondrocytes, etc. In addition, RS is observed in cells derived from embryonic tissues, in cells from adults of all ages, and in cells taken from many animals: mice, chickens, Galapagos tortoises, etc. (reviewed in Hayflick, 1994). The number of CPDs cells undergo in culture varies considerably between cell types and species. Early results suggested a relation between CPDs cells could endure and the longevity of the species from which the cells were derived. For example, cells from the Galapagos tortoise, which--as <a href="aging_animals.html">described</a>--can live over a century, divide about 110 times (Goldstein, 1974), while mouse cells divide roughly 15 times (Stanley et al., 1975; Rohme, 1981)--but see more recent studies below. In addition, cells taken from patients with progeroid syndromes such as Werner syndrome (WS)--<a href="genetics_of_aging.html">described elsewhere</a>--endure far fewer CPDs than normal cells (Salk et al., 1981). Exceptions exist and certain cell lines can divide indefinitely without reaching RS. These are said to be "immortal" and include embryonic germ cells and most cell lines derived from tumors, such as HeLa cells (Brunmark et al., 1986; Chen and Yu, 1994; Pera et al., 2000). Some types of rat cells have also been claimed as capable of evading RS (Mathon et al., 2001; Tang et al., 2001), and more recently some mouse cells have been found to be immortal under certain culture conditions (Parrinello et al., 2003), as detailed below.</p>
        </div>
        <div ref="biomarkers">
        <blockquote><H2>Biomarkers of Cell Senescence</H2></blockquote>

        <p align="justify">The discovery of RS sparked considerable interest and the phenotype of cell senescence in human fibroblasts has been characterized by a series of features, termed biomarkers (reviewed in Campisi, 1999; Campisi and
          d'Adda di Fagagna, 2007). The most obvious biomarker is growth arrest, i.e., cells stop dividing, which can be detected by different methods. Even vigorously dividing cultures are heterogeneous and contain a percentage of growth-arrested cells; this percentage progressively increases until all cells in the population are quiescent, that is, they have stopped dividing (Cristofalo and Sharf, 1973; Smith and Whitney, 1980); interestingly, the percentage of growth-arrested cells is higher in cells from patients with progeroid syndromes, such as WS cells, when compared with normal cells at the same CPD (Kill et al., 1994). Senescent cells are growth arrested in the transition from phase G1 to phase S of the cell cycle (Sherwood et al., 1988). The growth arrest in RS is irreversible in the sense that growth factors cannot stimulate the cells to divide (reviewed in Cristofalo and Pignolo, 1993), even though senescent cells can remain metabolically active for long periods of time (reviewed in Goldstein, 1990).</p>

        <p align="justify">Another important biomarker is cellular morphology (Fig. 1). While cells age in vitro they endure  progressive morphological changes (e.g., Bayreuther et al., 1988). Briefly, senescent cells are bigger and a senescent population has more diverse morphotypes than cells at earlier CPDs. In fact, a confluent senescent culture has a smaller cellular density than a confluent young culture, though this also occurs because senescent cells are more sensitive to cell-cell contact inhibition.</p>

        <p align="center" ><img src="../assets/senescent_fibroblasts.jpg" width="363" height="133" border="0"></p>

        <blockquote><p align="justify"><strong>Figure 1:</strong> Normal human fibroblasts (left) and fibroblasts showing a senescent morphology (three cells on the right). Notice the common elongated morphology of senescent cells.</P></blockquote>

        <p align="justify">One widely-used marker of RS is senescence-associated &#946;-galactosidase (SA &#946;-gal) activity. The enzyme &#946;-galactosidase, a lysosomal hydrolase, is normally active at pH 4, but in senescent cells it often happens for &#946;-galactosidase to be active at pH 6 which can be detected with a simple biochemical assay. Both in vitro and in vivo, the percentage of cells positive for SA &#946;-gal increases with, respectively, CPDs and age (Dimri et al., 1995). Conversely, in immortal cell lines, such as HeLa tumor cells, the percentage of cells positive for SA &#946;-gal does not correlate with CPDs. The increase in SA &#946;-gal also correlates with the appearance of the senescent morphotypes (Toussaint et al., 2000). Lysosomes are organelles that break down cellular junk. Early reports showed that lysosomes increase in number and size in senescent cells (Robbins et al., 1970; Brunk et al., 1973). SA &#946;-gal appears to be a result of increased lysosomal activity at a suboptimal pH, which becomes detectable in senescent cells due to an increase in lysosomal content (Kurz et al., 2000). Other results also suggest that during in vitro aging increased autophagy--i.e., digestion of the cell's organelles; <a href="causes_of_aging.html">discussed elsewhere</a>--may be associated with an increase of lysosomal mass and SA &#946;-gal (Gerland et al., 2003).</p>

        <p align="justify">Normal human cells are diploid, which means they have two copies of each chromosome. With each subcultivation the percentage of polyploid cells--i.e., with three or more copies of chromosomes--has been shown to increase (Matsumura, 1980). Deletions in the mitochondrial DNA (mtDNA) have also been observed both during RS (Dumont et al., 2000a) and during aging in vivo, at least in some tissues (Corral-Debrinski et al., 1992; Yang et al., 1994; Liu et al., 1998).</p>

        <p align="justify">The expression levels of several genes change during in vitro cellular aging (reviewed in Cristofalo et al., 1998a; Campisi and d'Adda di Fagagna, 2007). One important type of gene overexpressed in senescent cells are inflammatory regulators like interleukin 6 (IL6) (Shelton et al., 1999; de Magalhaes et al., 2004); some studies support a role for proinflammatory proteins  secreted by senescent cells in driving senescence, which may lead to positive feedback loops and to senescence induction in normal cells near senescent cells (Acosta et al., 2008; Kuilman et al., 2008; Freund et al., 2010). Senescent cells also display an increased activity of metalloproteinases which degrade the extracellular matrix (reviewed in Campisi, 1999). On the other hand, senescent cells  have a decreased ability to express heat shock proteins (Choi et al., 1990; Bonelli et al., 1999).</p>

        <p align="justify">Telomeres are non-coding regions at the tips of chromosomes. In vertebrates, they are composed of repeated sequences of TTAGGG (Moyzis et al., 1988; Meyne et al., 1989). During in vitro aging, the telomeres shorten gradually in each subcultivation (Harley et al., 1990). The same process might occur in vivo too (Hastie et al., 1990; Lindsey et al., 1991; Allsopp et al., 1992). Telomere shortening is the primary cause of RS in human fibroblasts, and given their importance, telomeres and their role in aging are discussed in detail in <a href="telomeres_telomerase.html">another essay</a>.</p>
        </div>
        <div ref="stress">
        <blockquote><H2>Stress-Induced Premature Senescence</H2></blockquote>

        <p align="justify">Assuming human fibroblasts endure 50 CPDs, 2<sup>50</sup> is more than enough cells for several lifetimes (Hayflick, 1994). However, a number of factors can accelerate and/or trigger cell senescence, one of which is oxidative stress. Normally, cell culture conditions include 20% oxygen (O<sub>2</sub>) and these were the conditions initially used by Hayflick and Moorhead and most subsequent studies. When human fibroblasts are cultured at 3% O<sub>2</sub>, which is closer to physiological conditions, they achieve a further 20 CPDs (Chen et al., 1995). Conversely, different types of human cells cultured above 20% O<sub>2</sub> display a reduced growth rate and endure fewer CPDs (Horikoshi et al., 1986 & 1991; von Zglinicki et al., 1995). If O<sub>2</sub> is above 50%, in fact, it becomes cytotoxic (Horikoshi et al., 1991). The way subcytotoxic stress can accelerate the appearance of the senescent phenotype in cells has been deemed as another form of cellular senescence called stress-induced premature senescence (SIPS; see Fig. 2) (Brack et al., 2000).</p>

        <div align="center"><p><img src="../assets/SIPS.gif" alt="SIPS" width="630" height="161" border="0"></p></div>

        <blockquote>
          <p align="justify"><strong>Figure 2:</strong> Schematic drawing of SIPS. Source: <a href="http://www.fundp.ac.be/sciences/biologie/urbc/Gras/gras_homepage.html">Ageing and Stress Group</a>, University of Namur, Belgium.</P></blockquote>

        <p align="justify">Not surprisingly, depending on the dose of stressor used, a cell population will react in different ways. For instance, a high cytotoxic dosage will cause such an amount of damage that cellular biochemical activities decrease leading to cellular death by necrosis. The level of damage sustained by cells determines whether programmed cell death--apoptosis--can unfold or, if the damage is lower, senescence. Since a cellular population is not homogeneous, the dosage of the stressor will shift the percentage of cells executing each of the possible programs depending on the amount of stress, respectively, from no stress to high stress: cellular proliferation, senescence, apoptosis, and necrosis (reviewed in Toussaint et al., 2002a).</p>

        <p align="justify">In addition to O<sub>2</sub>, other sources of oxidative damage, such as H<sub>2</sub>O<sub>2</sub> and tert-butylhydroperoxide, and other stressors--e.g., ethanol, ionizing radiations, and mitomycin C--can induce SIPS in many types of proliferative cells such as lung and skin fibroblasts, endothelial cells, melanocytes, and retinal pigment epithelial cells (reviewed in Toussaint et al., 2002b; Dierick et al., 2003). The list of stressors that can cause SIPS is constantly growing. Instead of chronic stress, SIPS can be induced based on a single or repeated short exposure(s) to stressors. Oncogenes such as <em>ras</em> can also induce senescence (Serrano et al., 1997). As discussed below, because organisms and cells are constantly being exposed to stressors, senescent cells in vivo may derive not only from cell divisions but from cells being exposed to stress.</p>
        </div>
        <div ref="senesc">
        <blockquote><H2>Senescent Cells, Stress and Organismal Aging</H2></blockquote>

        <p align="justify">The connection between organismal aging and cell senescence remains a subject of controversy, in spite of decades of study (reviewed in Hayflick, 1994; de Magalhaes, 2004; Campisi, 2005; Campisi and d'Adda di Fagagna, 2007; Jeyapalan and Sedivy, 2008; de Magalhaes and Passos, 2018). Below I present and discuss some of the key arguments for and against a role of RS and senescent cells in human aging.</p>

        <p align="justify">At least <em>post partum</em>, there is no relation between the number of CPDs cells can endure and the age of the donor (Cristofalo et al., 1998b). Chances are previous studies showing otherwise were biased (Cristofalo, 2001). Likewise, one study in centenarians failed to find differences in the CPDs cells taken from centenarians could endure when compared to cells from young donors (Tesco et al., 1998). As mentioned above, cells at birth from patients with certain progeroid syndromes have fewer divisions than cells from healthy controls. This, however, might be a result of increased cell death or exit from the cell cycle for reasons unrelated to RS (Johnson et al., 1999). In fact, senescent cells from patients with Werner's syndrome have different patterns of gene expression (Oshima et al., 1995; Toda et al., 1998) and biomarkers of senescence (Schulz et al., 1996); similar findings have been reported in Hutchinson-Gilford progeria (Park et al., 2001). I should also point out that a caveat of comparing CPDs is that when cell lines are derived from people, the selected cells are those that grow because people, even very old people, never run out of proliferating cells (Tesco et al., 1998; Cristofalo, 2001). As such, these studies would not detect, say, differences in the proportion of proliferating cells.</p>

        <p align="justify">Although a relation between a species' longevity and the CPDs its cells can endure in vitro exists, it is debatable if this is related to aging. For one, optimal culture conditions vary from species to species. As an example, O<sub>2</sub> partial pressure can affect cellular proliferation and there is evidence that O<sub>2</sub> limits the replicative capacity of mouse fibroblasts as these are immortal under low O<sub>2</sub> (Parrinello et al., 2003). As such, comparisons between different species may be biased due to intra-species differences in O<sub>2</sub> sensitivity (Toussaint et al., 2002b). In addition, due to the positive correlation between body size and longevity--mentioned <a href="comparative_biology.html">before</a>--, perhaps cells taken from long-lived animals endure more CPDs because of differences in size, not due to differences in longevity, as supported by results using more sophisticated methods (Lorenzini et al., 2005; Seluanov et al., 2008).</p>

        <p align="justify">Senescent cells and senescence-associated biomarkers can be found in various human tissues in vivo associated with both aging and pathology (Paradis et al., 2001; Going et al., 2002; Minamino et al., 2003; Campisi, 2005; Jeyapalan and Sedivy, 2008). Interestingly, stress-prone tissues appear to be the most affected. For example, fibroblasts cultured from distal lower extremities of patients with venous reflux, which precedes the development of venous ulcers, display characteristics of senescent cells (Mendez et al., 1998). Similar results also relate cellular senescence to atherosclerosis (Minamino et al., 2002) and benign prostatic hyperplasia, a common age-related male pathology (Castro et al., 2003). One study found that the number of senescent fibroblasts increases exponentially with age in the skin of baboons and senescent cells are >15% of all cells in very old animals (Herbig et al., 2006). In the mouse liver, one study estimated that over 20% of hepatocytes were potentially senescent (Panda et al., 2008). Senescent cells have been found in other mouse tissues too, though possibly through telomere-independent mechanisms (Wang et al., 2009). Markers of cell senescence, such as p16<sup>INK4a</sup> which is discussed <a href="telomeres_telomerase.html">elsewhere</a>, have been found in the mouse brain (Molofsky et al., 2006; Jurk et al., 2012) and pancreas (Krishnamurthy et al., 2006), potentially contributing to age-dependent decline in regeneration. A gene expression meta-analysis across mammalian tissues and species found signatures of senescent cells in aged tissues (de Magalhaes et al., 2009b). However, one study monitored p16<sup>INK4a</sup> expression with age in mice and found that, while its expression increases with age, total body p16<sup>INK4a</sup> expression does not predict overall mortality, raising questions about the role of senescent cells in aging (Burd et al., 2013).</p>

        <p align="justify">Because senescent cells can secrete proinflammatory cytokines and other factors that disrupt the tissue microenvironment, they may contribute to disruption of cell and tissue function. Even a small percentage of senescent cells, in fact, may interfere with tissue homeostasis and function (Shay and Wright, 2000). Indeed, some evidence exist that senescent cells contribute to age-related pathologies such as osteoarthritis (Martin and Buckwalter, 2002; Price et al., 2002) and to skin aging (Giacomoni et al., 2000). Repeated stimulation of WI-38 human fibroblasts with pro-inflammatory cytokines interleukin-1 &alpha; (IL-1&alpha;) or tumor necrosis factor-&alpha; (TNF-&alpha;) induces SIPS (Dumont et al., 2000b). These cytokines' circulating levels increase in vivo (reviewed in Lio et al., 2003), favoring inflammation and perhaps contributing to SIPS in vivo; senescent cells might then also contribute to increase inflammatory levels, creating a positive feedback loop.</p>

        <p align="justify">Studies using genetically-modified mice found that genetic clearance of senescent cells delays aging-associated disorders in old mice (Baker et al., 2011; Baker et al., 2016). Initially this was observed in progeroid mice that exhibit accelerated aging and accumulate more senescent cells than normally (Baker et al., 2011). Clearance of senescent cells also did not extend lifespan in progeroid mice, which Baker et al. claim is due to their mice dying primarily of heart disease which is not affected by the treatment. More recently, using the same genetic approach, the same group found that removing senescent cells in mice preserves health in some tissues, though not in others, protects from cancer and extends median (but not maximum) lifespan (Baker et al., 2016). Therefore, these landmark studies provide evidence that senescent cells can promote age-related phenotypes, at least to a subset of organs.</p>

        <p align="justify">Clearly, senescent cells can be found in vivo without telomere shortening (Melk et al., 2003). Since cells taken from old donors do not endure fewer CPDs, one hypothesis is that senescent cells in vivo are not widely caused by shortening telomeres but instead by various stressors and insults. Exemplifying, studies in centenarians have raised doubts on whether telomere shortening occurs in vivo and whether senescence-associated genes in vitro are also differentially expressed in vivo (Mondello et al., 1999). Besides, some data indicate that chronic stressors may accelerate risk of a host of age-related diseases by prematurely aging the immune response (Kiecolt-Glaser et al., 2003). Lastly, as hinted by the above mentioned results on the impact of O<sub>2</sub> in cell proliferation, RS for many cell lines in vitro and in vivo might instead be better defined as SIPS resulting from oxidative stress.</p>

        <p align="justify">A relationship appears to exist between stress resistance and aging. In <a href="aging_models.html">model organisms</a>, extended longevity is often associated with increased stress resistance (reviewed in Longo, 1999). Concisely, manipulations in <em>C. elegans</em> that extend longevity show a strong correlation with resistance to stress (Murakami et al., 2000). In <em>Drosophila</em> too some mutations can increase longevity and augment stress resistance (Lin et al., 1998). Cell lines from long-lived mouse strains are also stress resistant (Salmon et al., 2005) and stress resistance in vitro correlates with mammalian longevity, at least for some stressors (Kapahi et al., 1999; Harper et al., 2007); similar results have been observed in birds (Harper et al., 2011). Cells from older individuals are more susceptible to stress and exhibit higher levels of biomarkers of senescence in general (Dekker et al., 2009). Finally, cells taken from patients with progeroid syndromes are more susceptible to stress (Gebhart et al., 1988), as not surprisingly are late passage fibroblasts (Yuan et al., 1996). Of course, it is not known whether these relationships are causal or not. Nevertheless, aging and stress resistance appear to be inversely related and so an association between cellular stress resistance and organismal aging is a possibility.</p>

        <p align="justify">There is no doubt that changes occur with age at a cellular level. Some genetic interventions regulating aging appear to influence tissue homeostasis by affecting senescence, cell proliferation, and cell death (reviewed in de Magalhaes and Faragher, 2008), as detailed in the context of the <a href="programmed_aging.html">endocrine theory of aging</a>. Results from mice suggest that systemic factors can influence aging, but only to some degree (Conboy et al., 2005), showing that intrinsic cellular mechanisms no doubt play a role in aging. In some tissues, such as the immune system, decreased proliferative ability may play a role in age-related degeneration (reviewed in Effros, 1996). Successive transplants of spleen and bone marrow yielded far from conclusive results but it appears that a slight decrease in proliferative ability does occur in vivo in spite the cells having had to divide much more than 50 times (Strehler, 1999, p. 53). Renewal of cardiomyocytes in humans declines with age (Bergmann et al., 2009). Therefore, mechanisms of aging intrinsic to cells no doubt exist (de Magalhaes, 2004). These may be related to the senescent phenotype but no doubt to other processes too. It was initially reported that cells from older donors have a slower proliferative capacity (Waters and Walford, 1970; Hayflick, 1994). This effect, known as the latent period, occurs because fewer cells are in the replication cycle, not because they take longer to divide (Ponten et al., 1983; Karatza et al., 1984), but it has also been under attack (Cristofalo et al., 1998b). One study argued that cells ceasing division is not relevant to aging. Instead, altered gene expression, resulting from quality control defects that allow errors to accumulate as cells divide, leads to cells with diminished function (Ly et al., 2000). </p>

        <p align="justify">Overall, it is clear that RS is not a faithful model of aging changes occurring in vivo (Gershon and Gershon, 2000a for arguments). In fact, RS is widely recognized as an anti-cancer mechanism (Wynford-Thomas, 1999; de Magalhaes, 2013; de Magalhaes and Passos, 2018), as further <a href="telomeres_telomerase.html">debated elsewhere</a>. Recent results also suggest a role for senescent cells during development (Munoz-Espin et al., 2013; Storer et al., 2013; Davaapil et al., 2017) and wound healing (Demaria et al., 2014). Senescent cells also appear to have benefits in promoting insulin secretion by pancreatic beta cells (Helman et al., 2016). That is not to say, however, that senescent cells cannot play a role in some aspects of aging. One hypothesis is that while RS evolved as an anti-cancer mechanism, the accumulation of senescent cells contributes to aging (Campisi, 2005; Jeyapalan and Sedivy, 2008; de Magalhaes, 2013). While there is little evidence to suggest that cells running out of divisions are a major factor in aging, it is possible that stress and various insults trigger cell senescence in vivo. Even a small fraction of senescent cells in organs may impair tissue renewal and homeostasis, decrease organ function, and contribute to the aging phenotype, as shown by the studies genetically ablating senescent cells (Baker et al., 2011; Baker et al., 2016). As such, there is some evidence that accumulating senescent cells might promote a subset of the aging phenotype, and clearly senescent cells may contribute to age-related pathologies or at the very least reflect damage to tissues.. Because telomere shortening is the main cause of RS in human fibroblasts, this topic is further debated in context of the role of <a href="telomeres_telomerase.html">telomeres in aging</a>.</p>
        </div>
        <div ref="stem">
        <blockquote><H2>Stem Cells and Germ Cells</H2></blockquote>

        <p align="justify">Stem cells are found in different places throughout the body and participate in tissue homeostasis by replacing differentiated cells that die; due to their high place in tissues' hierarchy, stem cells are promising subjects for study in the context of aging. Some human stem cells can express <a href="telomeres_telomerase.html">telomerase</a> (Chiu et al., 1996; Sugihara et al., 1999), indicating that the most actively dividing cell lines in the body overcome telomere shortening--though somatic stem cells can show senescence in vitro (Smith and Schofield, 1994) and in vivo (Martin et al., 2000). Interestingly, a correlation between mean telomeres and age is found in the first two decades for muscle satellite cells--a type of muscle stem cell--but not afterwards (Decary et al., 1997). Consequently, one hypothesis is that somatic cells can only divide a limited amount of times but are constantly being replenished by stem cells. Interestingly, satellite cells in mouse muscle become senescent-like with age due to p16<sup>INK4a</sup> activation, perhaps contributing to loss of homeostasis and regeneration in old muscle (Sousa-Victor et al., 2014). Furthermore, one study found a correlation between stem cell turnover and mice lifespan (de Haan and Van Zant, 1999), meaning that perhaps stem cell senescence influences organismic senescence (Snyder and Loring, 2005). Mechanisms of stem cell aging are also of great interest and have been linked to various processes, including <a href="causes_of_aging.html">DNA damage</a> (Rossi et al., 2007; Freitas and de Magalhaes, 2011) and <a href="telomeres_telomerase.html">telomeres</a>. At present this is only one hypothesis but no doubt unraveling the role of stem cells in aging is a major avenue for future research. As mentioned <a href="engineering_aging.html">elsewhere</a>, stem cells may also have anti-aging applications.</p>

        <p align="justify">As <a href="aging_animals.html">previously mentioned</a>, the doctrine of the immortal germplasm claims that germ cells are immortal and can divide forever (Weismann, 1891; Kirkwood, 1977). A prediction of such hypothesis is that the germ cells should have increased stress resistance and repair mechanisms (Kirkwood, 1977). Experimental evidence, however, is contradictory: the soma of <i>Drosophila</i> has been reported to be more sensitive to mutagens (Vogel and Zijlstra, 1987); increased DNA repair has been documented in male mice germ cells (Walter et al., 1994), but using ionizing radiation no difference in sensibility was found between mice male germ cells and bone marrow (van Loon et al., 1993). It has also been proposed that meiosis and gametogenesis can have recombinational and other genetic events that contribute to a rejuvenation not possible in differentiated somatic cells (Medvedev, 1981; Holliday, 1984), yet little or no evidence exists to support such claims. Furthermore, the common notion that germ cells have improved DNA repair mechanisms and thus avoid aging is itself debatable (reviewed in Walter et al., 2003).</p>
        </div>
      </b-col>

    </b-row>


  </b-container>


</template>
<script>
import Footer from "./AppFooter";

export default {
  components: {Footer},
  methods: {
    goto(refName) {
      var element = this.$refs[refName];
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
};
</script>
<style>
h2 {
  padding-top: 30px;
}

.sidebar {
  position: -webkit-sticky;
  position: sticky;
  top: 3%;
}

</style>
