<!--TODO: Make left nav float-->
<template>
  <b-container fluid="sm">
    <b-row class="text-left">
      <b-col class="text-left" cols="2">
        <div class="sidebar">
          <b-card>
            <b-nav vertical>
              <b-nav-item @click="goto('intro')">Introduction</b-nav-item>
              <b-nav-item @click="goto('orgel')">Orgel's Hypothesis, Protein Damage and Autophagy</b-nav-item>
              <b-nav-item @click="goto('energy')">Energy Metabolism and Aging</b-nav-item>
              <b-nav-item @click="goto('free')">Free Radical Theory</b-nav-item>
              <b-nav-item @click="goto('dna')">DNA Damage</b-nav-item>
              <b-nav-item @click="goto('free')">Free Radical Theory</b-nav-item>
              <b-nav-item @click="goto('dna')">DNA Damage</b-nav-item>
            </b-nav>
          </b-card>
        </div>
      </b-col>
      <b-col>
        <div ref="intro">
        <h2>Damage-Based Theories of Aging</h2>

        <blockquote>
          <p align="justify">One class of <a href="aging_theories.html">theories of aging</a> is based on the concept that damage, either due to normal toxic by-products of metabolism or inefficient repair/defensive systems, accumulates throughout the entire lifespan and causes aging. In this essay, I present and review the most important of these damage-based theories.</P>

          <p><em>Keywords:</em> ageing, anti-oxidants, biogerontology, error catastrophe theory of aging, hypotheses, life span, proteostasis</p></blockquote>

        <hr width="80%" size="1">

        <p align="justify">The general idea behind damage-based theories of aging is that a slow build-up of damage, perhaps even from conception (Gavrilov and Gavrilova, 2001), eventually leads to failure of the system which can be seen as failure of a critical organ like the heart or the whole body. It is useful to point out, however, that some authors (e.g., Olson, 1987; Holliday, 2004; Kirkwood, 2005) defend that aging is a result of many forms of damage accumulation, and hence that aging is due to an overlap of the mechanistic theories of aging described below.</P>
        </div>
        <div ref="orgel">
        <blockquote><H2>Orgel's Hypothesis, Protein Damage and Autophagy</H2></blockquote>

        <p align="justify">Aging has long been seen as a result of errors of many kind. An early attempt to develop a theory engulfing the genetic and protein machineries was Orgel's hypothesis (Orgel, 1963). Essentially, his idea was that errors in transcription from DNA lead to errors in proteins which build-up over time and cause more errors in transcription, creating an amplifying loop that eventually kills the cell and leads to aging. Errors in DNA repair would also affect the accuracy of the flow of information in cells (Orgel, 1973). Indeed, damaged proteins accumulate with age, and enzymes lose catalytic activity with age (Gershon and Gershon, 1970). This can lead to cellular dysfunction and accumulation of other forms of damage. On the other hand, Orgel's hypothesis has been regarded as unlikely to be correct for various reasons: feeding abnormal amino acids to animals to increase the number of errors in proteins does not result in a shorter lifespan (Strehler, 1999, p. 293); errors in macromolecular synthesis also do not appear to increase with age (Rabinovitch and Martin, 1982); <em>in vitro </em>aging cultured fibroblasts do not have increased protein errors (Harley et al., 1980)--and, in fact, <a href="cell_aging.html">cellular senescence</a> appears to be caused by other mechanisms. Presently, Orgel's hypothesis is largely discarded. </P>

        <p align="justify">Even though Orgel's hypothesis failed the test of time, some age-related diseases could be due to protein defects and accumulating protein errors (e.g., see Lee et al., 2006; Morimoto, 2006) and a role for protein dysfunction in aging is a possibility. For example, in flies, the accumulation of protein aggregates is associated with muscle with impaired muscle function with age (Demontis and Perrimon, 2010). Proteasomes are protein complexes that degrade other proteins; their expression decreases with age (Lee et al., 1999) and this has been implicated as a factor contributing to aging (Friguet et al., 2000; Tomaru et al., 2012). Also, the half-life of proteins is longer in older animals (Friguet et al., 2000). One study found evidence that proteins involved in protein degradation are under selection in lineages where longevity increased (Li and de Magalhaes, 2013). Two studies found evidence that protein stability and protein homeostasis are enhanced in long-lived bats and in the naked mole-rat when compared to mice (Perez et al., 2009; Salmon et al., 2009), yet another study found no evidence that protein repair and recycling are correlated with longevity in 15 species of birds and mammals (Salway et al., 2011). Therefore, the results are not conclusive but this is an area where further studies are warranted.</P>

        <p align="justify">Autophagy is a process by which the cell digests its own organelles and components. Recent studies, in particular genetic manipulations in <a href="aging_models.html">model organisms</a>, point towards a role of autophagy in aging (reviewed in Cuervo et al., 2005; Rubinsztein et al., 2011). In flies, disruption of autophagy shortens (Juhasz et al., 2007) while enhanced autophagy increase lifespan (Simonsen et al., 2008). Manipulation of autophagy-related genes has also been associated with longevity in yeast (Tang et al., 2008). There is in fact evidence that longevity-associated pathways, such as GH/IGF1 that is <a href="programmed_aging.html">detailed elsewhere</a> and TOR (which some <a href="antiaging_science.html">anti-aging interventions</a> target), influence autophagy (Toth et al., 2008; Salminen and Kaarniranta, 2009; Kamada et al., 2010; Neufeld, 2010), though the causality of these links remains to be established since autophagy is related to other processes too. Dysfunction of autophagy has also been linked to neurodegenerative disorders (Wong and Cuervo, 2010). In mouse liver, autophagy declines with age and its maintenance through genetic manipulation can improve the ability of cells to handle protein damage, resulting in lower levels of damaged proteins and improved organ function (Zhang and Cuervo, 2008). While a lot of works remains to elucidate the role of autophagy in aging, it does appear that protein homeostasis is important for longevity and its dysfunction could contribute to aging (Morimoto and Cuervo, 2009).</P>
        </div>
          <div ref="energy">
        <blockquote><H2>Energy Metabolism and Aging</H2></blockquote>

        <p align="justify">In 1908, physiologist Max Rubner discovered a relationship between metabolic rate, body size, and longevity. In brief, long-lived animal species are on average bigger--as <a href="comparative_biology.html">detailed</a> before--and spend fewer calories per gram of body mass than smaller, short-lived species. The energy consumption hypothesis states that animals are born with a limited amount of some substance, potential energy, or physiological capacity and the faster they use it, the faster they will die (Hayflick, 1994). Later, this hypothesis evolved into the rate of living theory: the faster the metabolic rate, the faster the biochemical activity, the faster an organism will age. In other words, aging results from the pace at which life is lived (Pearl, 1928). This hypothesis is in accordance with the life history traits of mammals in which a long lifespan is associated with delayed development and slow reproductive rates (reviewed in Austad, 1997a & 1997b).</p>

        <p align="justify">As previously <a href="genetics_of_aging.html">mentioned</a>, <a href="caloric_restriction.html">caloric restriction</a> (CR) is one of the most important discoveries in aging research. Although the mechanisms behind CR remain a subject of discussion (see below), since it involves a decrease in calories, one hypothesis put forward by George Sacher is that maybe CR works by delaying metabolic rates, in accordance with the energy consumption hypothesis (reviewed in Masoro, 2005). Body temperature is crucial to determine metabolic rate since the rate of chemical reactions rises with temperature. One common feature of animals, such as mice, rats, and monkeys, under CR is a lower body temperature (Weindruch and Walford, 1988; Ramsey et al., 2000), which is consistent with the energy consumption hypothesis. On the other hand, some studies in rodents suggest that CR can extend lifespan without reducing metabolic rate (Masoro, 2005). For example, some evidence indicates that mice under CR burn the same amount of energy as controls, suggesting they have similar metabolic rates. These studies, however, remain controversial in the way metabolic rate is normalized to metabolic mass (McCarter and Palmer, 1992). An alternative hypothesis is that CR shifts metabolic pathways (Duffy et al., 1990). More recent results suggest that previous studies used unreliable estimates of metabolic mass in their calculations and indeed CR changes metabolic rates, supporting the rate of living hypothesis (Greenberg and Boozer, 2000), yet the debate has not been settled.</p>

        <p align="justify">Several experiments have cast doubts on the energy consumption hypothesis. For instance, rats kept at lower temperatures eat 44% more than control mice and yet do not age faster (Holloszy and Smith, 1986). In fact, mice with higher metabolic rates may live slightly longer (Speakman et al., 2004). Mutations in the tau protein in hamsters increase metabolic rates and extends lifespan (Oklejewicz and Daan, 2002). Lastly, as <a href="comparative_biology.html">detailed before</a>, metabolic rates, when correctly normalized for body size, do not correlate with longevity in mammals (de Magalhaes et al., 2007a).  Despite its intuitive concept, the rate of living theory is practically dead. Based on observations from CR, it is likely that energy metabolism plays a role in aging but, as described below, it is not clear how this occurs. One hypothesis is that energy metabolism is linked to insulin-signaling, as mentioned <a href="programmed_aging.html">ahead</a>.</p>
        </div>
        <div ref="free">
        <blockquote><H2>The Free Radical Theory of Aging</H2></blockquote>

        <p align="justify">Free radicals and oxidants--such as singlet oxygen that is not a free radical--are commonly called reactive oxygen species (ROS) and are such highly reactive molecules that they can damage all sorts of cellular components (Fig. 1). ROS can originate from exogenous sources, such as ultraviolet (UV) and ionizing radiations, and from several intracellular sources. The idea that free radicals are toxic agents was first suggested by Rebeca Gerschman and colleagues (Gerschman et al., 1954). In 1956, Denham Harman developed the free radical theory of aging (Harman, 1956; Harman, 1981). Since oxidative damage of many types accumulate with age (e.g., Ames et al., 1993), the free radical theory of aging simply argues that aging results from the damage generated by ROS (reviewed in Beckman and Ames, 1998).</p>

        <div align="center"><p><img src="../assets/ROS.gif" alt="ROS and aging" width="616" height="129" border="0"></p></div>

        <blockquote><p align="justify"><strong>Figure 1:</strong> ROS or reactive oxygen species can be formed by different processes including normal cell metabolic processes. Due to their high reactivity, ROS can damage other molecules and cell structures. The free radical theory of aging argues that oxidative damage accumulates with age and drives the aging process.</P></blockquote>

        <p align="justify">To protect against oxidation there are many different types of antioxidants, from vitamins C and E to enzymes such as superoxide dismutase (SOD), catalase, and glutathione peroxidase. Briefly, antioxidant enzymes are capable of degrading ROS into inert compounds through a series of chemical reactions (Ames et al., 1981; Ames et al., 1993). The simple existence of enzymes to prevent damage by ROS is a strong indicator that ROS are biologically important, dangerous molecules (de Magalhaes and Church, 2006).</p>

        <p align="justify">Most experimental evidence in favor of the free radical theory of aging comes from invertebrate <a href="aging_models.html">models of aging</a>. Transgenic fruit flies, <em>Drosophila melanogaster</em>, overexpressing the cytoplasmic form of SOD, called Cu/ZnSOD or SOD1, and catalase have a 34% increase in average longevity and a delayed aging process (Orr and Sohal, 1994). More recent findings, however, suggest that the influence of SOD1 and catalase in <em>Drosophila</em> aging may had been overestimated because the authors only took into account short-lived strains (Orr et al., 2003). Overexpressing bovine SOD2, the mitochondrial form of SOD, also called MnSOD, in <em>Drosophila</em> slightly extends average longevity but does not delay aging (Fleming et al., 1992). Also in <em>Drosophila</em>, expression of SOD1 in motor neurons increases longevity by 40% (Parkes et al., 1998) and overexpression in neurons of thioredoxin, a protein involved in reduction-oxidation (redox) reactions that can act as an antioxidant, increased lifespan by 15% (Umeda-Kameyama et al., 2007). Certain long-lived strains of both <em>Drosophila</em> (Rose, 1989; Hari et al., 1998) and the nematode worm <em>Caenorhabditis elegans</em> (Larsen, 1993) have increased levels of antioxidant enzymes. On the other hand, evidence against the free radical theory has also emerged from invertebrate models. Briefly, deletion of SOD2 in <em>C. elegans</em> surprisingly extends lifespan (Van Raamsdonk and Hekimi, 2009), and long-lived ant queens actually have lower levels of SOD1 (Parker et al., 2004). Overexpression of SOD2 and catalase decreased the mitochondrial ROS release and increased resistance to oxidative stress in <em>Drosophila</em> yet decreased lifespan (Bayne et al., 2005).</p>

        <p align="justify">In addition to antioxidants, some enzymes catalyze the repair caused by ROS. One of such enzymes is methionine sulfoxide reductase A (MSRA), which catalyzes the repair of protein-bound methionine residues oxidized by ROS. Overexpression of MSRA in the nervous system of <em>Drosophila</em> increases longevity (Ruan et al., 2002) while mice without MSRA have a decreased longevity of about 40% (Moskovitz et al., 2001). Whether the aging process is affected remains to be seen (de Magalhaes et al., 2005), although the results from <em>Drosophila</em> suggest that age-related decline is also delayed by MSRA overexpression. Another enzyme that repairs oxidative damage is 8-oxo-dGTPase, which repairs 8-oxo-7,8-dihydroguanine, an abundant and mutagenic form of oxidative DNA damage. But contrary to the results involving MSRA, when researchers knocked out the gene responsible for 8-oxo-dGTPase, although the mutated mice had an increased cancer incidence, their aging phenotype did not appear altered (Tsuzuki et al., 2001).</p>

        <p align="justify">Targeted mutation of p66<sup>shc</sup> in mice has been reported to increase longevity by about 30%, inducing resistance to oxidative damage, and maybe delaying aging (Migliaccio et al., 1999). Although the exact function of p66<sup>shc</sup> remains unclear, some evidence suggests it may be related to intracellular oxidants and apoptosis (Nemoto and Finkel, 2002; Trinei et al., 2002; Napoli et al., 2003). Also, transgenic mice overexpressing the human thioredoxin gene featured an increased resistance to oxidative stress and an extended longevity of 35% (Mitsui et al., 2002). Like p66<sup>shc</sup>, mammalian thioredoxin regulates the redox content of cells and is thought to have anti-apoptotic effects (Saitoh et al., 1998; Kwon et al., 2003). More recent results suggest modest effects of thioredoxin overexpression on the lifespan of male mice and no effects on the lifespan of females (Perez et al., 2011). Neither p66<sup>shc</sup> nor thioredoxin are &quot;traditional&quot; antioxidants, so these findings could be unrelated to the free radical theory of aging but rather, for instance, tissue homeostasis. Mice with extra catalase in their mitochondria lived 18% more than controls and were less likely to develop cataracts, but they did not appear to age slower and their extended lifespan appeared to derive from a decrease in cardiac diseases throughout the entire lifespan (Schriner et al., 2005). Recently, mice overexpressing human MTH1, an enzyme that eliminates oxidized precursors from the dNTP pool, had lower levels of oxidative damage to DNA and were modestly (by ~15%) long-lived (De Luca et al., 2013). Lastly, the phenotype witnessed in a strain called senescence-accelerated mice may be related to free radical damage (Edamatsu et al., 1995; Mori et al., 1998).</p>

        <p align="justify">Experiments in feeding mice antioxidants--either a single compound or a combination of compounds--were able to decrease oxidative damage and increase average longevity but none of them clearly delayed aging (Harman, 1968; Comfort et al., 1971; Heidrick et al., 1984; Saito et al., 1998; Holloszy, 1998; Quick et al., 2008), while other studies did not conclude that feeding mice antioxidants increases longevity (e.g., Lipman et al., 1998). Several attempts have been made to overexpress or knock-out antioxidants in mice, but the results have been largely disappointing (Sohal et al., 2002; de Magalhaes, 2005a; de Magalhaes and Church, 2006; Lapointe and Hekimi, 2010). Often animals do not show any differences in their aging phenotype when compared to controls (Reaume et al., 1996; Ho et al., 1997; Schriner et al., 2000). In one of the most elegant experiments to test the free radical theory of aging, knockout mice heterozygous for SOD2 showed increased oxidative damage at a cellular and molecular level but did not show significant changes in longevity or rate of aging (Van Remmen et al., 2003). Ubiquitous overexpression of SOD1 in mice also failed to increase longevity (Huang et al., 2000). These results suggest that antioxidant proteins are already optimized in mammals. Indeed, correlations between rate of aging and antioxidant levels in mammals are, if they exist, very weak (reviewed in Finch, 1990; Sohal and Weindruch, 1996). Some studies found correlations between the levels of certain antioxidants and longevity in mammals, but failed to find any consensus (Tolmasoff et al., 1980; Ames et al., 1981; Cutler, 1985; Sohal et al., 1990). The long-lived naked mole-rat does not appear to have higher levels of antioxidants when compared to mice (Andziak et al., 2005). The way antioxidants can increase longevity but do not affect rate of aging suggests that antioxidants may be healthy but do not affect the aging process, as debated <a href="antiaging_science.html">elsewhere</a>.</p>

        <p align="justify">Although ROS can have several sources, some argue that ROS originating in the cellular metabolism which takes place in the cell's energy source, the mitochondrion, are the source of damage that drives aging. Since ROS are a result of cellular metabolism, the free radical theory of aging has been associated with the rate of living theory (Harman, 1981). One mechanism proposed for CR is that animals under CR produce less ROS and therefore age slower (Weindruch, 1996; Masoro, 2005), but since the rate of living theory seems out-of-favor this perspective will not be further discussed here. An alternative hypothesis is that the rate of mitochondrial ROS generation, independently of metabolic rates or antioxidant levels, may act as a longevity determinant (Sohal and Brunk, 1992; Barja, 2002). Some results suggest that the rate of ROS generated in the mitochondria of post-mitotic tissues helps explain the differences in lifespan among some animals, particularly among mammals (Ku et al., 1993; Barja and Herrero, 2000; Sohal et al., 2002; Lambert et al., 2007) and between birds and mammals (reviewed in Barja, 2002). One pitfall of these studies is that technical limitations exist in measuring ROS production in isolated mitochondria. For example, none of these studies measures the levels of hydroxyl radical, the most reactive and destructive of the ROS; often, hydrogen peroxide and superoxide anion are measured since they can react to give the hydroxyl radical. Even so, such studies may not be representative of what actually occurs. Moreover, two studies in <em>Drosophila</em> found that lowering ROS leakage from the mitochondria either did not result in a longer lifespan (Miwa et al., 2004) or even resulted in a shorter lifespan (Bayne et al., 2005). On the other hand, <a href="comparative_biology.html">comparative genomics</a> studies have revealed several associations between features of mitochondrial DNA (mtDNA) across species and longevity (de Magalhaes, 2005b; Moosmann and Behl, 2008; Nabholz et al., 2008; Aledo et al., 2011), suggesting that changes to mitochondrial proteins may be involved in the evolution of long lifespans, though further studies are necessary to elucidate the mechanisms involved.</p>

        <p align="justify">Several pathologies in mice and humans derive from mutations affecting the mitochondrion, which often involve an increase in ROS leakage from the mitochondrion (Pitkanen and Robinson, 1996; Wallace, 1999; DiMauro and Schon, 2003). Yet these pathologies do not result in an accelerated aging phenotype, but frequently result in diseases of the central nervous system (Martin, 1978). One example is Friedreich's ataxia which appears to result from increased oxidative stress in mitochondria and does not resemble accelerated aging (Rotig et al., 1997; Wong et al., 1999). Deficiency of the mitochondrial complex I has been reported in a variety of pathologies such as neurodegenerative disorders (reviewed in Robinson, 1998). Cytochrome c deficiency has also been associated with neurodegenerative disorders (reviewed in DiMauro and Schon, 2003) as has selective vitamin E deficiency (Burck et al., 1981). Rats selected for high oxidative stress develop cataracts from an early age (Marsili et al., 2004); other pathologies, such as heart changes and brain dysfunctions, have been described in these animals (Salganik et al., 1994), yet it is unclear whether they can be considered progeroid. Perhaps ROS are involved in some pathologies involving post-mitotic cells, such as neurons. Another hypothesis is that mitochondrial diseases affect mainly the central nervous system due to its high energy usage (Parker, 1990 for arguments). There is some evidence of a mitochondrial optimization in the human lineage to delay degenerative diseases, but not necessarily aging (de Magalhaes, 2005b). Interestingly, both <em>Drosophila</em> and <em>C. elegans</em> are mostly composed of post-mitotic cells, which can explain why results from these invertebrates are  more supportive of the free radical theory of aging than results from mice.</p>

        <p align="justify">Although it is undeniable that ROS play a role in several pathologies, including age-related pathologies like cataracts (Wolf et al., 2005), the exact influence of ROS in mammalian aging is debatable. It is plausible that ROS play a role in age-related degeneration of energy-rich tissues such as the brain; the brain may also be more susceptible to ROS because of its abundance of redox-active metals. One study found that superoxide dismutase/catalase mimetics prevented cognitive defects and oxidative stress in aged mice (Clausen et al., 2010). A similar study found that a SOD mimetic administered from middle age attenuated oxidative stress, improved cognitive performance, and extended lifespan by 11% (Quick et al., 2008). In conclusion, there is little direct evidence that ROS influence mammalian aging except perhaps in specific tissues such as the brain. Lastly, a changing paradigm is that ROS are not only damaging compounds but crucial in many cellular functions and thus it is the deregulation of pathways managing ROS that can contribute to aging rather than merely damage accumulation with age (de Magalhaes and Church, 2006).</p>
        </div>
        <div ref="dna">
        <blockquote><H2>The DNA Damage Theory of Aging</H2></blockquote>

        <p align="justify">The DNA, due to its central role in life, was bound to be implicated in aging (Fig. 2). One hypothesis then is that damage accumulation to the DNA causes aging, as first proposed by Failla in 1958 (Failla, 1958) and soon after developed by physicist Leo Szilard (Szilard, 1959). The theory has changed over the years as new types of DNA damage and mutation are discovered, and several theories of aging argue that DNA damage and/or mutation accumulation causes aging (reviewed in Gensler and Bernstein, 1981; Vijg and Dolle, 2002; Hoeijmakers, 2009; Freitas and de Magalhaes, 2011). Because DNA damage is seen as a broader theoretical framework than mutations, and DNA damage can lead to mutations, the current focus is on DNA damage and thus the theory herein is referred to as DNA damage theory of aging.</p>

        <p align="justify">It is well-established that DNA mutations/alterations--many often irreversible--and chromosomal abnormalities increase with age in mice (Martin et al., 1985; Dolle et al., 1997; Vijg, 2000; Dolle and Vijg, 2002) and humans (e.g., Esposito et al., 1989; Lu et al., 2004). Experiments in mice also suggest that DNA damage accumulates with age in some types of stem cells and may contribute to loss of function with age (Rossi et al., 2007). Long-lived mutant mice and animals under CR seem to have a lower mutation frequency, at least in some tissues (Garcia et al., 2008). Similarly, longevity of worm strains correlates with DNA repair capacity (Hyun et al., 2008). It is impossible, however, to tell whether these changes are effects or causes of aging. Correlations have been found between DNA repair mechanisms and rate of aging in some mammalian species (Hart and Setlow, 1974; Grube and Burkle, 1992; Cortopassi and Wang, 1996). In theory, even a slight increase in DNA repair rate over a large period of time and hundreds of cell divisions will have major consequences and could contribute to determine rate of aging. On the other hand, it has been argued that such correlations may be an artifact of long-lived species being on average bigger (Promislow, 1994). </p>

        <p align="justify">As mentioned <a href="genetics_of_aging.html">elsewhere</a>, progeroid syndromes are rare genetic diseases that appear to be accelerated aging. Interestingly, the most impressive progeroid syndromes, Werner's, Hutchinson-Gilford's, and Cockayne syndrome originate in genes that are related to DNA repair/metabolism (Martin and Oshima, 2000; de Magalhaes, 2005a; Freitas and de Magalhaes, 2011). Werner's syndrome (WS) originates in a recessive mutation in a gene, <em>WRN</em>, encoding a RecQ helicase (Yu et al., 1996; Gray et al., 1997). Since WRN is unique among its protein family in also possessing an exonuclease activity (Huang et al., 1998), it seems to be involved in DNA repair. Although the exact functions of WRN remain a subject of debate, it is undeniable that WRN plays a role in DNA biology, particularly in solving unusual DNA structures (reviewed in Shen and Loeb, 2000; Bohr et al., 2002; Fry, 2002). In fact, cells taken from patients with WS have increased genomic instability (Fukuchi et al., 1989). Topoisomerases are enzymes that regulate the supercoiling in duplex DNA. WS cells are hypersensitive to topoisomerase inhibitors (Pichierri et al., 2000). As such, WS is an indicator that alterations in the DNA over time play a role in aging.</p>

        <p align="justify">As with WRN, the protein whose mutation causes Hutchinson-Gilford's syndrome is also a nuclear protein: lamin A/C (Eriksson et al., 2003). Recent results also suggest that some atypical cases of WS may be derived from mutations in lamin A/C (Chen et al., 2003). The exact functions of lamin A/C remain unknown, but it appears to be involved in the biology of the inner nuclear membrane. Some evidence suggests that the DNA machinery is impaired in Hutchinson-Gilford's syndrome (Wang et al., 1991; Sugita et al., 1995), again suggesting that changes in the DNA are important in these diseases and, maybe, in normal aging. The protein involved in Cockayne Syndrome Type I participates in transcription and DNA metabolism (Henning et al., 1995). Other progeroid syndromes exist, though the classification is subjective. For example, Nijmegen breakage syndrome, which derives from a mutated DNA double-strand break repair protein (Carney et al., 1998; Matsuura et al., 1998; Varon et al., 1998), has been considered as progeroid (Martin and Oshima, 2000). </p>

        <p align="justify">Ample mouse models of accelerated aging have implicated genes involved in DNA repair such as the mouse homologues of xeroderma pigmentosum, group D (de Boer et al., 2002), ataxia telangiectasia mutated or ATM (Wong et al., 2003), p53 (Donehower et al., 1992; Donehower, 2002; Tyner et al., 2002; Cao et al., 2003), and Ercc1 (Weeda et al., 1997). Thus many progeroid syndromes in mice involve the DNA machinery (Hasty et al., 2003; de Magalhaes, 2005a). (I should note that most of the aforementioned genes, as well as other genes implicated in accelerated aging in mice, are described in the   <a href="http://genomics.senescence.info/genes/">GenAge database</a>.) Taken together, results from progeroid syndromes in mice and man support the DNA damage theory of aging. One hypothesis is that DNA damage accumulation with age triggers cellular signalling pathways (Fig. 2), such as  apoptosis, that result in a faster depletion of stem cells which in turn contributes to accelerated aging (Freitas and de Magalhaes, 2011).</p>

        <p align="justify">In spite of the progeroid syndromes described above, some genetic manipulations in mice have failed to support the theory. Mice deficient in Pms2, a DNA repair protein, had elevated mutation levels in multiple tissues yet did not appear to age faster than controls (Narayanan et al., 1997). Embryos of mice and flies irradiated with x-rays do not age faster (reviewed in Cosgrove et al., 1993; Strehler, 1999), though one report argued that Chernobyl victims do (Polyukhov et al., 2000). One classic study contradicting the DNA damage theory of aging showed that haploid wasps exposed to DNA damage have, as expected, a shorter lifespan than diploid wasps, but in a normal environment haploid and diploid wasps have same lifespan (Clark and Rubin, 1961), which should not be the case if DNA damage accumulation causes aging. Certain mutations in DNA repair proteins, such as p53 in humans (Varley et al., 1997), despite affecting longevity and increasing cancer incidence, fail to accelerate aging.</p>

        <p align="center" ><img src="../assets/DNA_damage_aging.gif" width="540" height="630" border="0"></p>

        <blockquote>
          <p align="justify"><strong>Figure 2:</strong> In spite of various DNA repair mechanisms, DNA damage lead to mutations and other problems which in turn lead to cell loss and dysfunction. With age, this causes depletion of stem cell stocks and loss of homeostasis which drives organismal aging. (Adapted from Freitas and de Magalhaes, 2011).</P></blockquote>

        <p align="justify">An emerging hypothesis is that only specific types of DNA changes are crucial in aging, which would explain why mutations in some DNA repair genes affect aging while others do not. One study systematically analyzed DNA repair genes associated or not with aging and found that genes involved in non-homologous end joining are more often related to aging (Freitas et al., 2011). Emerging evidence also suggests that DNA damage that contributes to mutations and/or chromosomal aberrations increases the risk of cancer while DNA damage that interferes with transcription appears to contribute to aging possibly via effects on <a href="cell_aging.html">cellular aging</a> and cell signalling (Hoeijmakers, 2009). Taken together, the results from manipulations of DNA repair pathways in mice suggest that disruption of specific pathways, such as  nucleotide excision repair and non-homologous end joining, is more strongly associated with premature aging  phenotypes and may thus be more important to aging (Freitas and de Magalhaes, 2011).</p>

        <p align="justify">If the DNA damage theory of aging is correct, then it should be possible to delay aging in mice by enhancing or optimizing DNA repair mechanisms. Unfortunately, and in spite of numerous efforts (reviewed in de Magalhaes, 2005a), this crucial piece of evidence is still lacking. For example, mice overexpressing a DNA repair gene called <em>MGMT</em> had a lower cancer incidence but did not age slower (Zhou et al., 2001). Arguably the most compelling evidence comes from mice with extra copies of tumour suppressors. Mice with extra copies of p53 and INK4a/ARF--whose functions are <a href="telomeres_telomerase.html">described elsewhere</a>--lived 16% longer than controls but it was not clear if aging was delayed (Matheu et al., 2007). Interestingly, overexpressing telomerase in mice with enhanced expression of p53 and INK4a/ARF, which are cancer-resistant, results in an increase in lifespan up to 40% (Tomas-Loba et al., 2008). Whether aging is delayed in these animals or even if DNA repair is improved is unclear but these findings suggest some level of protection from age-related degeneration via optimization of pathways associated with cancer and DNA damage responses. Recently, overexpression in mice of BubR1, a protein that ensures accurate segregation of chromosomes, slightly extended lifespan and protected against cancer and aging, giving weight to the idea that genomic instability contributes to aging (Baker et al., 2013).</p>

        <p align="justify">One possibility is that ROS damage to DNA plays a role in aging. Some circumstantial evidence exists in favor of such hypothesis (Hamilton et al., 2001), yet given the aforementioned concerns regarding the role of ROS in aging this appears unlikely, except perhaps in specific tissues like the brain. Even though damage from free radicals to nuclear DNA remains an unproven cause of aging, since ROS originate in the mitochondrion, and since mitochondria possess their own genome, many advocates of the free radical theory of aging consider that oxidative damage to mitochondria and to the mtDNA is more important (Harman, 1972; Linnane et al., 1989; de Grey, 1997; Barja, 2002). Indeed, some evidence exists that under CR oxidative damage to mtDNA is more important than oxidative damage to nuclear DNA (reviewed in Barja, 2002). Mutations in mtDNA tend to accumulate with age in some tissues (Corral-Debrinski et al., 1992; Yang et al., 1994; Tanhauser and Laipis, 1995; Liu et al., 1998), though not necessarily caused by ROS (reviewed in Larsson, 2010; Kennedy et al., 2013). Likewise, nuclear mutations have been suggested to contribute to mitochondrial dysfunction (Hayashi et al., 1994). One study found that accumulating mutations to mitochondrial DNA are also unlikely to drive stem cell aging (Norddahl et al., 2011). At present, and despite contradictory evidence in favor (Khaidakov et al., 2003 for arguments) and against the theory (Rasmussen et al., 2003 for arguments), current technology does not appear capable of assessing the true relevance of damage to mtDNA in aging (Lightowlers et al., 1999; DiMauro et al., 2002). However, one study using next-generation sequencing found that no increase in mtDNA mutations with age in mice (Ameur et al., 2011).</p>

        <p align="justify">Interestingly, disruption of the mitochondrial DNA polymerase resulted in an accelerated aging phenotype in mice, for the first time directly implicating the mtDNA in aging (Trifunovic et al., 2004). This appears to be unrelated to oxidative damage, however, and instead result from increased apoptosis and accumulated mtDNA damage (Kujoth et al., 2005; Trifunovic et al., 2005). On the other hand, a mitochondrial mutator mouse with much higher mutation frequency than normal mice did not exhibit signs of accelerated aging, though it also failed to show increased levels of mitochondrial deletions (Vermulst et al., 2007). Mice with a mutation in a mtDNA helicase accumulate mitochondrial deletions and develop progressive external ophthalmoplegia, but do not age faster (Tyynismaa et al., 2005). More recently, maternally transmitted mtDNA mutations in mice induced mild aging phenotypes but also brain malformations (Ross et al., 2013). Mutations in mitochondrial DNA polymerase in humans result in mitochondrial disorders that, as in the context of the free radical theory of aging, typically affect the nervous system (Van Goethem et al., 2001; Tang et al., 2011), though other pathologies such as infertility (Rovio et al., 2001) have also been reported. As such, mtDNA may play a role in age-related diseases and aging (Wallace, 1992), though further research remains to confirm such hypothesis and elucidate the exact mechanisms involved.</p>

        <p align="justify">Animal cloning involving somatic cells to create new organisms is an interesting technique for gerontologists (e.g., Lanza et al., 2000; Yang and Tian, 2000). Clones from adult frogs do not show signs that differentiation affects the genome (Gurdon et al., 1975). Dolly was "created" by transferring the DNA-containing nucleus of a post-mitotic mammary cell into an egg and from there a whole new organism was formed. We know Dolly had some genetic (Shiels et al., 1999) and--possibly more crucially--epigenetic defects (Young et al., 2001), so maybe her arthritis and the pathologies leading to her death are a result of damage present in the DNA. Nonetheless, she was remarkably "normal," having endured a complete developmental process and being fertile (Wilmut et al., 1997). Moreover, mice have been cloned for six generations without apparent harm (Wakayama et al., 2000). Perhaps the highly proliferative nature of the embryo can, by recombination, dilute the errors present in the DNA, but results from cloning experiments suggest that at least some cells in the body do not accumulate great amounts of DNA damage. It would be interesting to further study the longevity of cloned animals.</P>

        <p align="justify">If progeroid syndromes represent a phenotype of accelerated aging then changes in DNA over time most likely play a role in aging, possibly through effects on cell dysfunction and loss that may involve stem cells (Freitas and de Magalhaes, 2011). Since many genetic perturbations affecting DNA repair do not influence aging, it is doubtful overall DNA repair is related to aging or that DNA damage accumulation alone drives aging. Understanding which aspects, if any, of DNA biology play a role in aging remains a great challenge in gerontology. Moreover, the next step to give strength to the DNA damage theory of aging would be to delay aging in mice based on enhanced DNA repair systems, but that has so far eluded researchers. In conclusion, changes in DNA over time may play an important role in aging, yet the essence of those changes and the exact mechanisms involved remain to be determined.</p>
        </div>
      </b-col>

    </b-row>


  </b-container>


</template>
<script>
import Footer from "./AppFooter";

export default {
  components: {Footer},
  methods: {
    goto(refName) {
      var element = this.$refs[refName];
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
};
</script>
<style>
h2 {
  padding-top: 30px;
}

.sidebar {
  position: -webkit-sticky;
  position: sticky;
  top: 3%;
}

</style>
