<!--TODO: Make left nav float-->
<template>
  <b-container fluid="sm">
    <b-row class="text-left">
      <b-col class="text-left" cols="2">
        <div class="sidebar">
          <b-card>
            <b-nav vertical>
              <b-nav-item @click="goto('intro')">Introduction</b-nav-item>
              <b-nav-item @click="goto('class')">Classical Evolutionary Theories of Aging</b-nav-item>
              <b-nav-item @click="goto('life')">Life History Theory</b-nav-item>
              <b-nav-item @click="goto('empirical')">Empirical Evidence</b-nav-item>
              <b-nav-item @click="goto('unique')">Unique Evolution</b-nav-item>
            </b-nav>
          </b-card>
        </div>
      </b-col>
      <b-col>
        <h2>Telomeres and Telomerase</h2>

        <blockquote>
          <p align="justify">Telomere shortening causes <router-link to="/cell-ageing">cellular senescence</router-link>, making it a major candidate mechanism for a role in aging and a target for <router-link to="/anti-ageing-medicine">anti-aging interventions</router-link>. In this essay, I review current knowledge on telomere biology and discuss the possible role of telomeres and telomerase in human aging and in cancer.</p>

          <p><em>Keywords:</em> ageing, biogerontology, cell aging clock, cytogerontology, terminal restriction fragments, TRF</p></blockquote>

        <hr width="80%" size="1">

        <blockquote><H2>Telomere Shortening As the Timekeeper of Cells</H2></blockquote>

        <p align="justify">Early studies by Hermann Muller and Barbara McClintock showed that the ends of chromosomes are capped by a structure called the telomere to prevent chromosome fusions (Muller, 1938; McClintock, 1941). In the 1970's, as the mechanisms behind DNA replication were becoming better understood, it became clear that DNA polymerase, the enzyme responsible for DNA replication, could not fully synthesize the 3' end of linear DNA (Fig. 1). In 1972, James Watson called this the end-replication problem (Watson, 1972). At about the same time, in a Moscow subway station, Alexey Olovnikov also recognized Watson's problem in an analogy between the track that represented the DNA and the train that represented DNA polymerase. Yet Olovnikov went further to propose that the end-replication problem would result in telomere shortening with each round of replication and that, because the DNA is replicated during cell division, this mechanism could be the cause of <router-link to="/cell-ageing">replicative senescence</router-link> (RS) (Olovnikov, 1971 & 1973). Soon after, studies by Leonard Hayflick and colleagues found that the nucleus controls RS (Wright and Hayflick, 1975; Hayflick, 1994).</p>

        <div align="center"><p><img src="end_replication_problem.gif" alt="The end-replication problem" width="413" height="322" border="0"></p></div>

        <blockquote>
          <p align="justify"><strong>Figure 1:</strong> DNA polymerase requires an RNA primer to initiate synthesis in the 5'-3' direction. At the end of a linear chromosome, DNA polymerase can synthesize the leading strand until the end of the chromosome. In the lagging strand, however, DNA polymerase's synthesis is based on a series of fragments, called Okazaki, each requiring an RNA primer. Without DNA to serve as template for a new primer, the replication machinery is unable to synthesize the sequence complementary to the final primer event. The result is an end-replication problem in which sequence is lost at each round of DNA replication.</P></blockquote>

        <p align="justify">Olovkikov's model turned out to be incredibly accurate. Telomere shortening is now considered the main causal mechanism of RS and telomere length is the molecular clock that counts the cumulative population doublings (CPDs) cells can endure (reviewed in Wright and Shay, 2001). Although it was previously known that telomere shortening occurs in each subcultivation (Harley et al., 1990), the key finding relating the telomeres to RS was made in 1998 by scientists from Geron Corporation. Telomerase is a reverse-transcriptase enzyme, discovered by Carol Greider and Elizabeth Blackburn, that elongates the telomeres and thus corrects the normal telomere erosion (Greider and Blackburn, 1985). It has two components: an RNA component (Feng et al., 1995) and a catalytic subunit (Nakamura et al., 1997). Telomerase activity parallels expression of the catalytic subunit (hTERT) and ectopic hTERT expression is sufficient to restore telomerase activity in human cells (Counter et al., 1998). Telomerase activity was shown in immortal cell lines (Counter et al., 1992). But the definitive breakthrough came when it was shown that expression of hTERT in human cells avoids RS (Bodnar et al., 1998). Human fibroblasts immortalized with hTERT divide vigorously, do not show increased staining for SA &#946;-gal--a marker of <router-link to="/cell-ageing">cell senescence</router-link>--, and do not show signs of neoplastic transformation (Jiang et al., 1999; Morales et al., 1999). Even expression of hTERT in late passage fibroblasts appears to reverse the loss of function characteristic of pre-senescent cells (Funk et al., 2000).</p>

        <p align="justify">Transient expression of hTERT for 7 CPDs in human fibroblasts elongated the shortest telomeres by 2.5 kilobase pairs (kbp). Afterwards, these cells divided for roughly 50 CPDs with a telomere shortening of 50 bp per division before reaching RS. These results strongly argued that telomere length, not hTERT expression, is the key to bypass RS (Steinert et al., 2000) and established telomere length as the clock that keeps track of CPDs and gives rise to <router-link to="/cell-ageing">RS and the Hayflick limit</router-link>. The 2009 Nobel Prize was awarded to Greider, Blackburn and Jack Szostak "for the discovery of how chromosomes are protected by telomeres and the enzyme telomerase" (for an overview see Varela and Blasco, 2010).</p>

        <p align="justify">Telomerase is not the only mechanism capable of elongating the telomeres. There are several immortal telomerase-negative cell lines with typically a great variety of telomere lengths (e.g., Bryan et al., 1995). Although the exact mechanisms behind what is called alternative lengthening of telomeres remain largely unknown, recombinational processes may be involved (McEachern and Blackburn, 1996; Dunham et al., 2000). Still, either using telomerase or not, all known immortal cell lines must stabilize their telomeres (reviewed in Colgin and Reddel, 1999; Stewart and Weinberg, 2000). Unicellular eukaryotes must also stabilize their telomeres. For example, defects in telomere replication have been shown to trigger senescence in yeast (Lundblad and Szostak, 1989) and in the protozoan Tetrahymena (Yu et al., 1990).</p>

        <blockquote><H2>How Telomere Dysfunction Induces Cellular Senescence</H2></blockquote>

        <p align="justify">Although telomere length regulates RS and can be seen as a mitotic clock, the mechanisms involved are more complex than they may seem at first. This section and the next provide a fairly detailed and technical discussed of the molecular mechanisms involved; the final section in this essay discusses the potential role of telomeres and telomerase in aging and cancer.</p>
        <p align="justify">Telomere length is neither the only nor the ultimate timekeeper of cells (reviewed in Blackburn, 2000). During telomerase-immortalization of human cell lines, several researchers noticed that immortalized cells had shorter telomeres than growth arrested controls (Ducray et al., 1999; Zhu et al., 1999). Surprisingly, these immortalized cells featured less chromosome fusions, which are the most noticeable outcome of short telomeres (Hande et al., 1999). Similarly, it was noticed in yeast that certain telomerase-negative strains would senesce with longer telomeres than immortal telomerase-positive strains (Prescott and Blackburn, 1997; Roy et al., 1998). Since telomere length alone could not explain these observations, other players had to be involved.</p>

        <p align="justify">Using electron microscopy, it was revealed that telomeres are not linear, but instead appear to form duplex loops, called t-loops (Fig. 2). Crucial in these loops are the telomeric repeat-binding factors TRF1 (van Steensel and de Lange, 1997) and TRF2 (Smogorzewska et al., 2000). In particular TRF2 can remodel linear telomeric DNA into t-loops (Griffith et al., 1999). Although not completely understood, the prevailing hypothesis is that these loops stabilize or cap the telomeres. Capping may protect the telomeres from being recognized as DNA damage. TRF2 protects telomeres (van Steensel et al., 1998): inhibition of TRF2 induces apoptotic cell death (Karlseder et al., 1999) while overexpression of TRF2 reduces the senescent checkpoint of cells in terms of telomere length (Karlseder et al., 2002). These results suggest that telomere capping, not just telomere length, is crucial in avoiding telomere dysfunction and preventing cell senescence. Results showing that telomerase disruption can slow cell proliferation and alter the 3' single-stranded telomeric overhang without telomere shortening support this view (Masutomi et al., 2003). One plausible hypothesis is that telomere shortening may destabilize or even prevent the capping of telomeres, leading to RS (Shay, 1999).</p>

        <div align="center"><p><img src="telomere.jpg" alt="Telomere cap" width="393" height="260" border="0"></p></div>

        <blockquote><p align="justify"><strong>Figure 2:</strong> Telomeric structure forming a loop that caps the end of telomeres. Rendered using <a to="http://pymol.sourceforge.net/">PyMOL</a>.</P></blockquote>

        <p align="justify">Whether the end-replication problem alone is responsible for telomere shortening is still under debate. RS can occur in human fibroblasts--often referred to as human diploid fibroblasts or HDFs--in the absence of cell division and short telomeres. Cells kept confluent for long periods of time--up to 12 weeks--exit the cell cycle. The small proportion of cells that continue dividing endured fewer CPDs than normal presumably due to compensatory cycling (Munro et al., 2001). Although quiescent cells do not appear to lose telomeres (von Zglinicki, 2000), cells endure an accelerated telomere shortening following extensive periods of confluency (Sitte et al., 1998). One hypothesis is that telomere dysfunction occurs in confluent cells despite lack of telomere shortening. Therefore, the end-replication problem as a model to explain telomere shortening may not be entirely correct. Telomeres end in a single-stranded G-rich 3'-overhang, presumably as a result of C-rich strand degradation during telomere processing (Wellinger et al., 1996; Makarov et al., 1997). Some results suggest that erosion of the overhang occurs at cell senescence and is prevented by telomerase expression. Progressive erosion appears to be a result of cell division and not an effect of RS (Stewart et al., 2003). As such, the exact molecular mechanisms behind telomere shortening and dysfunction remain undetermined.</p>

        <p align="justify">Since a normal human diploid cell contains 92 telomeres, another issue is whether it is mean telomere length or the shortest telomere to trigger RS. Evidence from mice indicates that the shortest telomeres, not mean telomere length, are responsible for inducing RS (Hemann et al., 2001). Yet one study  in human fibroblasts found that the onset of RS shows a better correlation with mean telomere length than with the shortest telomere (Martens et al., 2000).</p>

        <blockquote><H2>Uncapped Telomeres Recognized as DNA Damage</H2></blockquote>

        <p align="justify">Even before hTERT-derived immortalization, it was possible to immortalize human fibroblasts using viral genes such as the simian virus 40 (SV40) T-antigen, E1A and E1B from adenovirus, or the human papillomavirus E6 and E7 genes. The E1B and E6 proteins bind and inactivate the tumor suppressor protein p53 while E1A and E7 bind and inactivate the retinoblastoma protein (pRb) (Dyson et al., 1989; Werness et al., 1990). Immortalization requires E6 and E7 or E1A plus E1B, so both p53 and pRb must be inactive. SV40 immortalization is also dependent on inactivation of both p53 and pRb (Shay et al., 1991). These findings led to the present concept that two pathways are responsible for inducing <router-link to="/cell-ageing">cell senescence</router-link> (Fig. 3). Confirming these suspicions, inhibition of p53 and pRb by antisense technology caused cells to endure 50 CPDs more than normal (Hara et al., 1991).</p>

        <p align="justify">In agreement with its anti-oncogenic profile, pRb is a central regulator of cell cycle progression and its state of phosphorylation determines cell cycle regulation (Buchkovich et al., 1989; reviewed in Herwig and Strauss, 1997). Hyperphosphorylated pRb allows the cell cycle to proceed while hypophosphorylated pRb prevents cell cycle progression. Presumably, pRb operates through inactivation of the E2F family of transcription factors, responsible for transcription of several genes involved in G1/S transition and DNA synthesis (Weintraub et al., 1992; Campisi, 1999). Briefly, the phosphorylation of pRb is dependent on cyclin-dependent kinases (CDKs) that govern the progression through the various phases of the cell cycle (reviewed in Lees, 1995). Inactivation of the G1 CDKs, responsible for the phosphorylation of pRb, prevents transition from phase G1 to phase S and blocks the cell cycle, originating, for example, RS.</p>

        <p align="justify">Cyclin-dependent kinase inhibitors (CDKIs), as the name implies, inhibit the activity of CDKs. One of such proteins is p16<sup>INK4a</sup>, that disrupts and inhibits the activities of CDK4 and CDK6, thus preventing cell cycle progression (Hara et al., 1996). Exogenous expression of p16<sup>INK4a</sup> induces RS in young cells and in immortal cells without p53 activity (McConnell et al., 1998; Vogt et al., 1998). In addition, immortalization may also be achieved by disruption of both p16<sup>INK4a</sup> and p53 (Rogan et al., 1995). pRb is needed for growth suppression mediated by p16<sup>INK4a</sup> (Medema et al., 1995). These results suggest that p16<sup>INK4a</sup> acts upstream of pRb in regulating RS.</p>

        <p align="justify">Another important CDKI is p21<sup>WAF1</sup>, which also has the ability to block the cell cycle by inhibiting CDK2, CDK4, and CDK6 and thus preventing pRb phosphorylation (Harper et al., 1993 & 1995). p21<sup>WAF1</sup> can induce senescence independently of p16<sup>INK4a</sup> (McConnell et al., 1998; Vogt et al., 1998). Since p21<sup>WAF1</sup> expression levels increase in pre-senescent cells--i.e., before p16<sup>INK4a</sup> overexpression--, p21<sup>WAF1</sup> likely triggers senescence before p16<sup>INK4a</sup> (Tahara et al., 1995; Alcorta et al., 1996; Wong and Riabowol, 1996; Dulic et al., 2000). In contrast, p16<sup>INK4a</sup> remains overexpressed in senescent cells while p21<sup>WAF1</sup> levels wane (Stein and Dulic, 1998).</p>

        <p align="justify">p21<sup>WAF1</sup> is induced by p53 to trigger RS (reviewed in Wang et al., 2003). Briefly, p53 is a  transcription factor capable of acting both as a transcriptional activator and suppressor. Overexpression of p53 leads to cell cycle arrest or apoptosis (Sugrue et al., 1997). The induction of p53 by DNA-damaging agents led to the suggestion that p53 is a checkpoint factor that prevents cells from accumulating mutations by inducing apoptosis or growth arrest (reviewed in Ko and Prives, 1996). p53 may help maintain genetic stability (see Linke et al., 2003 for arguments). Increased levels of p53 have been associated with critically short telomeres (Vaziri and Benchimol, 1996; Gonzalez-Suarez et al., 2000). Thus p53 is probably responsible for recognizing dysfunctional telomeres--e.g., critically short telomeres--as DNA damage and triggering RS. Indeed, activation of p53 occurs as cells approach senescence (Atadja et al., 1995; Kulju and Lehman, 1995; Bond et al., 1996). Therefore, p53 appears to be the major initiator of senescence, while p16<sup>INK4a</sup> presumably maintains senescence (Alcorta et al., 1996; Dulic et al., 2000; Serrano and Blasco, 2001; Wang et al., 2003). Another possibility is that p16<sup>INK4a</sup> serves as a second barrier to prevent growth of cells with significantly damaged DNA (reviewed in Campisi and
          d'Adda di Fagagna, 2007).</p>

        <p align="justify">p16<sup>INK4a</sup> appears to be important in the response to DNA damage (Robles and Adami, 1998; Shapiro et al., 1998; te Poele et al., 2002) and other stimuli like oncogenic signals (Serrano et al., 1997). The immortalization of human epithelial cells requires inactivation of p16<sup>INK4a</sup>--or E7 expression to inhibit pRb--in addition to hTERT activity (Kiyono et al., 1998). Since under 2% O<SUB>2</SUB> epithelial cells can be immortalized with hTERT activity alone, it appears that stressful culture conditions may activate p16<sup>INK4a</sup> and induce senescence independently of the telomeres (Ramirez et al., 2001; Rheinwald et al., 2002). Lastly, p16<sup>INK4a</sup> does not appear to be involved in RS of at least some mouse cells (Smogorzewska and de Lange, 2002), indicating that the regulation of RS and telomere dysfunction in mouse and human cell lines is different, as suggested by others (Hamad et al., 2002; Kim et al., 2002). (RS in mouse cells will not be discussed in detail here.)</p>

        <div align="center"><p><img src="growth_arrest.gif" alt="Signal transduction in growth arrest" width="181" height="425" border="0"></p></div>

        <blockquote>
          <p align="justify"><strong>Figure 3:</strong> Simplistic overview of the signal transduction from critically short telomeres to irreversible growth arrest at the G1/S transition of the cell cycle. Telomere dysfunction causes an activation of DNA damage response pathways, such as an activation of p53. p53 in turn activates p21<sup>WAF1</sup> that blocks the actions of several CDKs preventing the phosphorylation of pRb. Without hyperphosphorylated pRb several critical genes in the G1/S transition are not transcribed, blocking the cell cycle. Adapted from (de Magalhaes, 2004).</P></blockquote>

        <p align="justify">Although Figure 3 and the discussion above provide an overview of the current knowledge of cell cycle regulation, it is likely other players exist. For instance, p53 itself may be upregulated. Although the issue is controversial, some evidence indicates that the <em>ATM</em> gene, or other players involved in DNA damage response, may be the "sensor" that detects telomere dysfunction and then regulates p53 (Vaziri et al., 1997; Rouse and Jackson, 2002). Other results suggest that a novel transcriptional element regulates cyclin D1, and possibly other senescence-associated genes, in senescence cells (Berardi et al., 2003).</p>

        <p align="justify">Immortalization with viral proteins is not as simple as it may seem at first. Infection of human fibroblasts with viral oncogenes results in an extended replicative lifespan after which cells enter a stage called crisis (reviewed in Goldstein, 1990; McCormick and Campisi, 1991; Wei and Sedivy, 1999). During crisis, cells proliferate but the proportion of cells entering apoptosis gradually increases and thus cell numbers eventually diminish (Macera-Bloch et al., 2002). Since both p53 and pRb/p16<sup>INK4a</sup> pathways are inactive and chromosomal instability and fusions are abundant, crisis is thought to emerge due to extremely short telomeres. Occasionally, immortal cells emerge from crisis with stabilized telomeres, normally involving telomerase activation (reviewed in Stewart and Weinberg, 2000; Mathon and Lloyd, 2001). In a sense, crisis can be seen as the ultimate consequence of telomere dysfunction since it occurs when the mechanisms that respond to short telomeres, like p53 and pRb, are inactive.</p>

        <p align="justify">One last point is that even assuming that the p53 and pRb/p16<sup>INK4a</sup> pathways explain RS, they do not entirely explain the gradual aging of cells in culture. One hypothesis is that cell populations become more heterogeneous as they age. For example, since the percentage of cells actively dividing decreases with CPD, it is normal that the cell population as a whole ages, without changes other than more cells entering RS.</p>

        <p align="justify">Overall, whatever changes occur during telomere dysfunction, the mechanisms triggering growth arrest appear to involve DNA damage pathways. As such, the most likely explanation is that dysfunctional telomeres are recognized as DNA damage and repairing the short telomeres leads to chromosome fusions. Although unidentified genes may also be involved (e.g., Blasco and Hahn, 2003; Yawata et al., 2003), the most widely accepted hypothesis is that the p53 and pRb/p16<sup>INK4a</sup> pathways collaborate to stop cellular proliferation derived from telomere shortening in normal human fibroblasts (Fig. 3). Probably, the p53 pathway involving p21<sup>WAF1</sup> is activated beforehand, while p16<sup>INK4a</sup> prevails under strong physiological stimuli or stress and to maintain cells growth arrested, a state also called quiescence.</p>

        <blockquote><H2>Aging, Cancer, and the Telomeres</H2></blockquote>

        <p align="justify">The role of telomeres in RS has led to suggestions that telomerase can be used as an <router-link to="/anti-ageing-medicine">anti-aging therapy</router-link> (reviewed in Fossel, 1996; Blasco, 2005; Shawi and Autexier, 2008). As mentioned <router-link to="/cell-ageing">before</router-link>, however, the relation between RS and organismal aging is controversial. Whether telomere shortening plays a role in human aging is a hotly-debated issue, as reviewed below.</p>

        <p align="justify">Most, not all, human somatic tissues have no detectable telomerase activity (reviewed in Collins and Mitchell, 2002). In the bone marrow, hematopoietic cells express telomerase. Telomerase activity is higher in primitive progenitor cells and then downregulated during proliferation and differentiation (Chiu et al., 1996). Other reports associate, normally low, levels of telomerase activity with human stem cells (Sugihara et al., 1999), though probably not mesenchymal stem cells (Zimmermann et al., 2003). Telomerase activity has been detected in some highly proliferating normal human somatic  cells; for instance, in skin cells (Harle-Bachor and Boukamp, 1996; Taylor et al., 1996), immune system cells (Counter et al., 1995; Morrison et al., 1996), and colorectal tissues (Tahara et al., 1999). A decline in telomerase activity was reported in blood mononuclear cells with age (Iwama et al., 1998). Human germ cells have been found to express hTERT (Kilian et al., 1997).</p>

        <p align="justify">As with <router-link to="/cell-ageing">replicative potential</router-link>, telomere length in vivo is very heterogeneous (Serra and von Zglinicki, 2002; Takubo et al., 2002). Telomere shortening in vivo has been reported in liver cells (Aikata et al., 2000), lymphocytes (Pan et al., 1997), skin cells (Lindsey et al., 1991), blood (Iwama et al., 1998), and colon mucosa (Hastie et al., 1990). For example, telomere shortening appears to impact on the function of immune T cells, and telomerase activators can restore a more youthful functional profile (reviewed in Effros, 2009). Other studies found weak correlations between donor age and telomere length (Allsopp et al., 1992; Kammori et al., 2002; Njajou et al., 2007), while some studies found no correlation at all (Mondello et al., 1999; Renault et al., 2002; Serra and von Zglinicki, 2002; Takubo et al., 2002; Nwosu et al., 2005). Long telomeres have been found in cells from centenarians (Franceschi et al., 1999). Taken as a whole, these results indicate that telomere length varies widely between individuals and between different tissues, and that telomere shortening may occur in some tissues in vivo in association with certain pathologies and with age; this is similar to what is observed for <router-link to="/cell-ageing">senescent cells</router-link>. An association between telomere length and mortality has been reported in people aged 60 and over (Cawthon et al., 2003), and telomere shortening appears to be accelerated in people living more stressful lives (Epel et al., 2004). While these results support the idea that telomere shortening is a marker of stress and age-related pathology, they do not prove that telomere shortening is a causal factor in aging. Lastly, although telomerase may prevent the accelerated clonal senescence of Werner's syndrome cells (Wyllie et al., 2000), it does not appear to fully reverse the WS phenotype (Choi et al., 2001).</p>

        <p align="justify">No connection appears to exist between the mean telomere length of cells and the longevity of mammalian species. Of all studied primates, humans appear to have the shortest telomeres and the longest lifespan (Kakuo et al., 1999; Steinert et al., 2002). Mice also have long telomeres and feature high telomerase activity in many organs, in contrast to humans (Prowse and Greider, 1995). Interestingly, inbred mice have long (Kipling and Cooke, 1990) while wild mice have short telomeres, suggesting telomere length does not affect organismal longevity (Hemann and Greider, 2000). In rodents, telomerase activity correlates negatively with lifespan but does not correlate with longevity (Seluanov et al., 2007). The largest comparative study of telomeres and telomerase, involving over 60 mammalian species, found that smaller, short-lived species tend to have long telomeres and high levels of telomerase. This suggests that short telomeres and suppression of telomerase are necessary for the evolution of large body sizes and longevity, presumably by suppressing cancer (Gomes et al., 2011).</p>

        <p align="justify">Though mean telomere length at birth does not correlate with longevity in birds, rate of telomere shortening in erythrocytes was reported to inversely correlate with bird longevity. Telomere shortening in a variety of tissues was also reported to correlate, though to a lesser extent, with mammalian longevity (Haussmann et al., 2003; Vleck et al., 2003). In fact, a correlation between erythrocyte longevity and organismal longevity was previously reported, suggesting that cells, in this case erythrocyte stem cells, from long-lived animals divide fewer times (Rohme, 1981). In zebra finches telomere length early in life was a good predictor of lifespan (Heidinger et al., 2012). One study in rodents, however, failed to find evidence of a correlation between rate of telomere shortening in vitro and longevity (Seluanov et al., 2008).</p>

        <p align="justify">Mice overexpressing telomerase have a higher cancer incidence and hence a shorter lifespan (Artandi et al., 2002). But mice lacking telomerase were viable up to six generations. Telomeres gradually shortened and cells from animals of generation four displayed aneuploidy and other chromosomal aberrations. Abnormalities were observed as early as in the third generation and late-generation animals showed a few signs of accelerated aging (Blasco et al., 1997; Rudolph et al., 1999); it is controversial whether these animals are aging faster or merely developing a variety of pathologies. All in all, these results suggest that telomerase activity could be crucial for the normal functioning of highly proliferative organs in mice (Lee et al., 1998). Nonetheless, telomere length and/or telomerase activity do not explain why humans age slower than other primates and live so much longer than mice. They may help explain, however, why mice have a much higher cancer incidence than humans (Blasco, 2005).</p>

        <p align="justify">Telomerase expression has been found in lobsters, a <router-link to="/ageing-animals">species</router-link> in which aging remains undetected (Klapper et al., 1998), though it could be due to molting. On the other hand, in the frog <em>Xenopus laevis</em>, another <router-link to="/ageing-animals">animal</router-link> with a slow rate of aging (Brocas and Verzar, 1961), not only a great variation in telomere length has been observed (Bassham et al., 1998), but telomere length can diminish from parents to offspring with no detectable consequences and despite telomerase activity in germ cells (Mantell and Greider, 1994). The way telomere length does not impact on the life history of cloned animals is also in contradiction with a role of telomeres in aging. For instance, scientists took cells from a 17-year old bull and allowed them to divide (Kubota et al., 2000); they then used cells at different stages of their <router-link to="/cell-ageing">replicative lifespan</router-link> to create clones and, surprisingly, it appears that the older cells with shorter telomeres are more efficient for generating clones. It would be interesting to know the longevity of these clones as well as that of cloned calves with extended telomeres (Lanza et al., 2000). Overall, maybe telomeres are the cellular clock, but judging from these results telomere length is not a major determinant of the aging process.</p>

        <p align="justify">As with <router-link to="/cell-ageing">RS</router-link>, telomere shortening is a tumor suppressor mechanism (de Magalhaes, 2004; Campisi, 2005; Deng et al., 2008; de Magalhaes, 2013). Tumor development is dependent on telomere stabilization, normally by telomerase (Chen et al., 2000). For example, telomerase activation has been associated with skin malignancy as a result of exposure to ultraviolet radiation (Ueda et al., 1997). In contrast, telomerase inhibition can induce senescence in some cancer cells (Shammas et al., 1999). Knocking-out telomerase in mice through deletion of its RNA component, while not preventing cancer (Blasco et al., 1997; Rudolph et al., 1999), appears to increase cancer resistance (Gonzalez-Suarez et al., 2000; Rudolph et al., 2001). On the other hand, telomerase overexpression in mice promoted cancer development (Gonzalez-Suarez et al., 2001; Artandi et al., 2002). In addition, the connection between telomere signaling pathways and cancer is obvious (reviewed in Fearon, 1997). The human Li-Fraumeni syndrome has been associated with mutations in p53 and is characterized by increased cancer incidence (reviewed in Varley et al., 1997). Human germline mutations in p53 are also associated with a major cancer risk (Hwang et al., 2003). Retinoblastoma is also recognized as hereditary cancer (Murphree and Benedict, 1984; Goodrich and Lee, 1993). Germline mutations in p16<sup>INK4a</sup> have too been implicated in familial melanoma (Hussussian et al., 1994).</p>

        <p align="justify">More debatable is the role of telomeres in animal aging (de Magalhaes and Toussaint, 2004a). As mentioned <router-link to="/cell-ageing">elsewhere</router-link>, senescent cells likely accumulate in some tissues and may contribute to organ disfunction yet telomere-independent mechanisms may play a more prominent role. Some genetic interventions that alter aging appear to influence tissue homeostasis by affecting senescence, cell proliferation, and cell death, yet such evidence is circumstantial (reviewed in de Magalhaes and Faragher, 2008). Evidence from genetic manipulation experiments of players involved in telomeric signal transduction (Fig. 3) is mixed (reviewed in de Magalhaes, 2004). Increasing the dosage in mice of INK4a/ARF (the gene coding the mouse homolog of p16<sup>INK4a</sup>) offers resistance against cancer but does not affect aging (Matheu et al., 2004). Another study found that INK4a/ARF induction in mice results in premature senescence and inhibits cell proliferation but does not induce cell senescence (Boquoi et al., 2015). There is some evidence that p53 may influence aging in mice (Donehower, 2002), as <router-link to="causes_of_aging.html">debated elsewhere</router-link>, but it is not clear the same is true for humans. Likewise, disruption of p63, a homologue of p53, appears to accelerate aging (Keyes et al., 2005), yet human defects in p63 do not (Celli et al., 1999). Mouse strains with increased levels of p53 and INK4a/ARF are long-lived (Matheu et al., 2007), though it is unclear whether their aging process is altered--as <router-link to="/ageing-definition">defined before</router-link>. Arguably the strongest evidence for a role of telomerase in aging comes from telomerase overexpressing mice also engineered to resist cancer via enhanced expression of p53 and INK4a/ARF as these are long-lived (Tomas-Loba et al., 2008). Even though it is not clear whether aging is delayed in these animals or the exact mechanisms, these findings do point towards some level of protection from age-related degeneration via optimization of pathways  associated with telomeres and RS. Telomerase gene therapy in old mice also modestly increased lifespan (Bernardes de Jesus et al., 2012). It should be noted, however, that telomerase may have functions independent of telomere elongation, such as in protecting mitochondria from stress (Ahmed et al., 2008). Another study showed that telomerase reactivation reverses degeneration in mice (Jaskelioff et al., 2011). However, this study was conducted in animals that have no telomerase to begin with and thus develop a number of pathologies. Benefits from reactivating telomerase in mice that become sick for lack of telomerase are hardly surprising or noteworthy.</p>

        <p align="justify">Dyskeratosis congenita is an inherited disease involving skin and bone marrow failure (reviewed in Marrone and Mason, 2003). It is caused by a mutation in the <em>DKC1</em> gene. Intriguingly, the protein encoded by <em>DKC1</em>, dyskerin, is a component of telomerase. Mutations in the RNA component of telomerase are associated with an autosomal dominant form of dyskeratosis congenita (Vulliamy et al., 2001). Families with this form of the disease are more severely affected in later generations, suggesting telomere shortening could be involved. Features of dyskeratosis congenita include bone marrow failure, which is the most usual cause of death, abnormal skin pigmentation, leukoplakia and nail dystrophy (Knight et al., 1998). The role of stem cells has also been suggested (Mason, 2003). As judged from the phenotype of dyskeratosis congenita, telomeres are crucial in rapidly proliferating tissues but it is unclear whether telomere shortening is involved in human aging. One study measured changes in telomere length in over 4,000 people over 10 years but found no association with mortality or morbidity (Weischer et al., 2014). Human epidemiological data suggest a causal role of both short and very long telomeres in cancer, heart disease and other age-related diseases (Codd et al., 2013), so some impact of telomere shortening in age-related diseases besides cancer cannot be excluded.</p>

        <p align="justify">In conclusion, it is unquestionable that <router-link to="/cell-ageing">cellular senescence</router-link> and telomere biology are important in cancer and may be suitable to develop anti-cancer treatments (reviewed in Campisi et al., 2001; Blasco and Hahn, 2003; Hahn, 2003; Lee and Schmitt, 2003; Wang et al., 2003; de Magalhaes, 2013). Whether these can aid in understanding human aging is unknown. Hopefully readers can make their own mind from the aforementioned discussion. My personal opinion is that cellular senescence, primarily caused by stress but to some degree perhaps also by telomere shortening, can contribute to aging and age-related diseases.  Indeed, a genetic variant of telomerase has been associated with longer telomeres and exceptional human longevity (Atzmon et al., 2010). Having said that, I am not convinced by the empirical evidence that telomere shortening and cell senescence are <router-link to="/ageing-theories">causes of aging</router-link>. They may be contributors or intermediaries, for example by enhancing the effects of other types of <router-link to="causes_of_aging.html">molecular damage</router-link>, but I see little evidence that targeting the telomeres and/or telomerase by itself will have much effect on human aging even if it might be helpful in the case of some specific pathologies. I also think that cellular studies are crucial to gerontology, yet so much focus on measuring cellular proliferation does not appear to me to be the best approach, as mentioned <router-link to="/cell-ageing">before</router-link>. Other methodologies are desperately needed to assess the role of cellular changes in organismal aging.</p>


      </b-col>

    </b-row>


  </b-container>


</template>
<script>
import Footer from "./AppFooter";

export default {
  components: {Footer},
  methods: {
    goto(refName) {
      var element = this.$refs[refName];
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
};
</script>
<style>
h2 {
  padding-top: 30px;
}

.sidebar {
  position: -webkit-sticky;
  position: sticky;
  top: 3%;
}

</style>
